
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-26T08:26:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4cab651acbaad7ff1801dfaa1fa26e5838d19ed0",
 "version": "1.18.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
