VERSION_MAJOR = 0
VERSION_MINOR = 4
VERSION_BUILD = 0
VERSION_INFO = (VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD)
VERSION_STRING = "%d.%d.%d" % VERSION_INFO

__version__ = VERSION_INFO
__version__ = "0.4.0rc1"
VERSION_STRING = "0.4.0rc1"

