
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-08T13:21:28-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a0b2a902cd5ea5de57cc30eeca17e125b91c67d",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
