
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-13T15:56:26+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7feadb0d18826f2b4c9d3c956db8982a86c88ad",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
