# This file automatically generated by
#    C:\Jenkins\workspace\python\python-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2019-09-27 09:18:54.757618
__version__ = '3.0.0a6'