---
jupyter:
  jupytext:
    cell_metadata_filter: all,-slideshow
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.1.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Conditioning on signs and active set

One of the first works in this line of conditional inference
is [Lee et al.](projecteuclid.org/euclid.aos/1460381681) which
considers the LASSO (squared-error loss) and conditions
on the active set and their signs.

The functions `full_model_inference` and `pivot_plot` below are just simulation utilities
used to simulate results in least squares regression. The underlying functionality
is contained in the function `selectinf.learning.core.infer_full_target`.

```{python collapsed=TRUE}
import functools

import numpy as np, pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

from selectinf.tests.instance import gaussian_instance # to generate the data
from selectinf.algorithms.api import lasso

```

We will know generate some data from an OLS regression model and fit the LASSO
with a fixed value of $\lambda$. In the simulation world, we know the
true parameters, hence we can then return
pivots for each variable selected by the LASSO. These pivots should look
(marginally) like a draw from `np.random.sample`. This is the plot below.

```{python}
np.random.seed(0) # for replicability

def simulate(n=200, 
             p=20, 
             s=5, 
             signal=(0.5, 1), 
             sigma=2, 
             alpha=0.1, 
             B=6000,
             verbose=False):

    # description of statistical problem

    X, y, truth = gaussian_instance(n=n,
                                    p=p, 
                                    s=s,
                                    equicorrelated=False,
                                    rho=0.5, 
                                    sigma=sigma,
                                    signal=signal,
                                    random_signs=True,
                                    scale=False)[:3]


    L = lasso.gaussian(X, y, 3.5 * np.sqrt(n))
    soln = L.fit()
    active_vars = soln != 0
    if active_vars.sum() > 0:
        projected_truth = np.linalg.pinv(X[:, active_vars]).dot(X.dot(truth))
        
        S = L.summary(truth=projected_truth)
        S0 = L.summary()

        pivot = S['pval'] # these should be pivotal
        pvalue = S0['pval']

        return pd.DataFrame({'pivot':pivot,
                             'pvalue':pvalue})
```

Let's take a look at what we get as a return value:

```{python}
while True:
    df = simulate(verbose=True)
    if df is not None:
        break
df.columns
```

```{python}
dfs = []
for i in range(30):
    df = simulate()
    if df is not None:
        dfs.append(df)
```

```{python}
fig = plt.figure(figsize=(8, 8))
results = pd.concat(dfs)
pivot_plot(results, fig=fig);
```

```{python collapsed=TRUE}

```
