---
# This playbook provisions the google compute engine topology.

- name:  "schema check and Pre Provisioning Activities on topology_file"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'common' }

- name:  "Provisioning Azure VM resources"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: "azure" }

- name: "Writing contents to file"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'gather_resources' }
