---
# This playbook provisions the duffy topology.

- name:  "schema check and Pre Provisioning Activities on topology_file"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'common' }

- name:  "Provisioning duffy resources"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'duffy' }

- name: "Gather resources to the RunDB"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'gather_resources' }
