---
# This playbook provisions the libvirt topology.

- name:  "schema check and Pre Provisioning Activities on topology_file"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'common' }

- name:  "Provisioning libvirt resources"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'libvirt' }

- name: "Writing contents to file"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'gather_resources' }
