---
# This playbook provisions the openshift topology.

- name:  "schema check and Pre Provisioning Activities on topology_file"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'common' }

- name:  "Provisioning openshift resources"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'openshift' }

- name: "Gather resources to the RunDB"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'gather_resources' }
