---
- name:  "schema check and Pre-Provisioning Activities on topology_file"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'common' }

- name:  "Provisioning VMware resources"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'vmware' }

- name: "Gather resources to the RunDB"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'gather_resources' }
