repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: debug-statements
      - id: flake8
        additional_dependencies: ["flake8-bugbear == 18.2.0"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.13
    hooks:
      - id: isort
        additional_dependencies: ["isort[pyproject]"]
