# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class MigrationPlan(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'href': 'str',
        'created': 'datetime',
        'plan': 'str'
    }

    attribute_map = {
        'href': '_href',
        'created': '_created',
        'plan': 'plan'
    }

    def __init__(self, href=None, created=None, plan=None):  # noqa: E501
        """MigrationPlan - a model defined in OpenAPI"""  # noqa: E501

        self._href = None
        self._created = None
        self._plan = None
        self.discriminator = None

        if href is not None:
            self.href = href
        if created is not None:
            self.created = created
        self.plan = plan

    @property
    def href(self):
        """Gets the href of this MigrationPlan.  # noqa: E501


        :return: The href of this MigrationPlan.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this MigrationPlan.


        :param href: The href of this MigrationPlan.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def created(self):
        """Gets the created of this MigrationPlan.  # noqa: E501

        Timestamp of creation.  # noqa: E501

        :return: The created of this MigrationPlan.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this MigrationPlan.

        Timestamp of creation.  # noqa: E501

        :param created: The created of this MigrationPlan.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def plan(self):
        """Gets the plan of this MigrationPlan.  # noqa: E501

        Migration Plan in JSON format  # noqa: E501

        :return: The plan of this MigrationPlan.  # noqa: E501
        :rtype: str
        """
        return self._plan

    @plan.setter
    def plan(self, plan):
        """Sets the plan of this MigrationPlan.

        Migration Plan in JSON format  # noqa: E501

        :param plan: The plan of this MigrationPlan.  # noqa: E501
        :type: str
        """
        if plan is None:
            raise ValueError("Invalid value for `plan`, must not be `None`")  # noqa: E501

        self._plan = plan

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MigrationPlan):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
