[tool.poetry]
name = "netmagus"
version = "0.7.8"
description = "Python module for JSON data exchange via files or RPC with the Intelligent Visibility NetMagus system."
authors = ["Richard Collins <richardc@intelligentvisibility.com>"]
license = "LGPL-3.0"
readme = "README.rst"
homepage = "https://www.intelligentvisibility.com/netmagus/"
repository = "https://github.com/sdispater/pendulum"
keywords = ["netmagus", "network", "automation", "netops"]
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: GNU Lesser General Public License v3 ",
    "or later (LGPLv3+)",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3.4",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Topic :: System :: Networking"
]

packages = [
    {include = "netmagus"}
]

[tool.poetry.dependencies]
python = "^3.5"
future = "^0.16.0"
autobahn = "^19.10.1"
autobahn-sync = "^0.3.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
tox = "^3.0"
coverage = "^4.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"