
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-30T10:04:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4f919db6c3fcdb67bfacda072e5767dc8492fa2",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
