
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-07T16:35:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "203800fb1e4eddb347a3d8c446d9a5db758928c0",
 "version": "0+untagged.574.g203800f"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
