
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-29T03:27:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9da32b84c3bb3d3cbb174192888b541be3e04a7",
 "version": "v0.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
