
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-02T15:26:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "07a7688282c0fa980bd3a9d0b402fcf20382578a",
 "version": "3.3.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
