
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-11T16:47:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "59b912cb6163a4f4022ee3e3034c87fec100edbd",
 "version": "0.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
