language: generic

env:
    global:
        - PYMODULE=edgedb
        - RELEASE_PYTHON_VERSIONS="3.7"

        - S3_UPLOAD_USERNAME=oss-ci-bot
        - S3_UPLOAD_BUCKET=magicstack-oss-releases
        - TWINE_USERNAME: magicstack-ci

branches:
    # Avoid building PR branches.
    only:
        - master
        - ci
        - releases
        - /^v\d+(\.\d+)*$/

matrix:
    fast_finish:
        true

    include:
        - os: linux
          dist: xenial
          sudo: true
          language: python
          python: "3.7"
          env: BUILD=quicktests

        # Build manylinux wheels.  Each wheel will be tested,
        # so there is no need for BUILD=tests here.
        # Also use this job to publish the releases and build
        # the documentation.
        - os: linux
          dist: xenial
          sudo: required
          language: python
          python: "3.6"
          env: BUILD=wheels,release
          services: [docker]

        - os: osx
          env: BUILD=quicktests,wheels PYTHON_VERSION=3.7.3

cache:
    pip: true
    directories:
        - build

before_install:
    - .ci/travis-before-install.sh

install:
    - .ci/travis-install.sh

script:
    - .ci/travis-tests.sh
    - .ci/travis-build-wheels.sh

deploy:
    - provider: script
      script: .ci/travis-release.sh
      on:
          tags: true
          condition: '"${BUILD}" == *release*'
