# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/travis/build/randovania/randovania/randovania/gui/game_patches_window.ui',
# licensing of '/home/travis/build/randovania/randovania/randovania/gui/game_patches_window.ui' applies.
#
# Created: Tue Oct  1 21:04:51 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_GamePatchesWindow(object):
    def setupUi(self, GamePatchesWindow):
        GamePatchesWindow.setObjectName("GamePatchesWindow")
        GamePatchesWindow.resize(466, 442)
        self.centralWidget = QtWidgets.QWidget(GamePatchesWindow)
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.include_menu_mod_check = QtWidgets.QCheckBox(self.centralWidget)
        self.include_menu_mod_check.setEnabled(True)
        self.include_menu_mod_check.setObjectName("include_menu_mod_check")
        self.verticalLayout.addWidget(self.include_menu_mod_check)
        self.include_menu_mod_label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.include_menu_mod_label.sizePolicy().hasHeightForWidth())
        self.include_menu_mod_label.setSizePolicy(sizePolicy)
        self.include_menu_mod_label.setMaximumSize(QtCore.QSize(16777215, 60))
        self.include_menu_mod_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.include_menu_mod_label.setWordWrap(True)
        self.include_menu_mod_label.setOpenExternalLinks(True)
        self.include_menu_mod_label.setObjectName("include_menu_mod_label")
        self.verticalLayout.addWidget(self.include_menu_mod_label)
        self.warp_to_start_check = QtWidgets.QCheckBox(self.centralWidget)
        self.warp_to_start_check.setObjectName("warp_to_start_check")
        self.verticalLayout.addWidget(self.warp_to_start_check)
        self.warp_to_start_label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warp_to_start_label.sizePolicy().hasHeightForWidth())
        self.warp_to_start_label.setSizePolicy(sizePolicy)
        self.warp_to_start_label.setMaximumSize(QtCore.QSize(16777215, 70))
        self.warp_to_start_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.warp_to_start_label.setWordWrap(True)
        self.warp_to_start_label.setObjectName("warp_to_start_label")
        self.verticalLayout.addWidget(self.warp_to_start_label)
        self.dark_aether_box = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_aether_box.sizePolicy().hasHeightForWidth())
        self.dark_aether_box.setSizePolicy(sizePolicy)
        self.dark_aether_box.setObjectName("dark_aether_box")
        self.gridLayout = QtWidgets.QGridLayout(self.dark_aether_box)
        self.gridLayout.setObjectName("gridLayout")
        self.varia_suit_spin_box = QtWidgets.QDoubleSpinBox(self.dark_aether_box)
        self.varia_suit_spin_box.setMaximum(60.0)
        self.varia_suit_spin_box.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.varia_suit_spin_box.setProperty("value", 6.0)
        self.varia_suit_spin_box.setObjectName("varia_suit_spin_box")
        self.gridLayout.addWidget(self.varia_suit_spin_box, 2, 1, 1, 1)
        self.varia_suit_label = QtWidgets.QLabel(self.dark_aether_box)
        self.varia_suit_label.setObjectName("varia_suit_label")
        self.gridLayout.addWidget(self.varia_suit_label, 2, 0, 1, 1)
        self.dark_suit_label = QtWidgets.QLabel(self.dark_aether_box)
        self.dark_suit_label.setObjectName("dark_suit_label")
        self.gridLayout.addWidget(self.dark_suit_label, 3, 0, 1, 1)
        self.dark_suit_spin_box = QtWidgets.QDoubleSpinBox(self.dark_aether_box)
        self.dark_suit_spin_box.setMaximum(60.0)
        self.dark_suit_spin_box.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.dark_suit_spin_box.setProperty("value", 1.2)
        self.dark_suit_spin_box.setObjectName("dark_suit_spin_box")
        self.gridLayout.addWidget(self.dark_suit_spin_box, 3, 1, 1, 1)
        self.dark_aether_label = QtWidgets.QLabel(self.dark_aether_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_aether_label.sizePolicy().hasHeightForWidth())
        self.dark_aether_label.setSizePolicy(sizePolicy)
        self.dark_aether_label.setWordWrap(False)
        self.dark_aether_label.setObjectName("dark_aether_label")
        self.gridLayout.addWidget(self.dark_aether_label, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.dark_aether_box)
        self.pickup_style_box = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickup_style_box.sizePolicy().hasHeightForWidth())
        self.pickup_style_box.setSizePolicy(sizePolicy)
        self.pickup_style_box.setObjectName("pickup_style_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pickup_style_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pickup_model_combo = QtWidgets.QComboBox(self.pickup_style_box)
        self.pickup_model_combo.setObjectName("pickup_model_combo")
        self.pickup_model_combo.addItem("")
        self.pickup_model_combo.addItem("")
        self.pickup_model_combo.addItem("")
        self.pickup_model_combo.addItem("")
        self.verticalLayout_2.addWidget(self.pickup_model_combo)
        self.pickup_data_source_label = QtWidgets.QLabel(self.pickup_style_box)
        self.pickup_data_source_label.setObjectName("pickup_data_source_label")
        self.verticalLayout_2.addWidget(self.pickup_data_source_label)
        self.pickup_data_source_combo = QtWidgets.QComboBox(self.pickup_style_box)
        self.pickup_data_source_combo.setObjectName("pickup_data_source_combo")
        self.pickup_data_source_combo.addItem("")
        self.pickup_data_source_combo.addItem("")
        self.pickup_data_source_combo.addItem("")
        self.verticalLayout_2.addWidget(self.pickup_data_source_combo)
        self.verticalLayout.addWidget(self.pickup_style_box)
        GamePatchesWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(GamePatchesWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 466, 21))
        self.menuBar.setObjectName("menuBar")
        GamePatchesWindow.setMenuBar(self.menuBar)

        self.retranslateUi(GamePatchesWindow)
        QtCore.QMetaObject.connectSlotsByName(GamePatchesWindow)

    def retranslateUi(self, GamePatchesWindow):
        GamePatchesWindow.setWindowTitle(QtWidgets.QApplication.translate("GamePatchesWindow", "Hello, world!", None, -1))
        self.include_menu_mod_check.setText(QtWidgets.QApplication.translate("GamePatchesWindow", "Include Menu Mod", None, -1))
        self.include_menu_mod_label.setText(QtWidgets.QApplication.translate("GamePatchesWindow", "<html><head/><body><p>Menu Mod is a pratice tool for Echoes, allowing in-game changes to which items you have and warping to all rooms.</p><p>See the <a href=\"https://www.dropbox.com/s/yhqqafaxfo3l4vn/Echoes%20Menu.7z?file_subpath=%2FEchoes+Menu%2Freadme.txt\"><span style=\" text-decoration: underline; color:#0000ff;\">Menu Mod README</span></a> for more details.</p></body></html>", None, -1))
        self.warp_to_start_check.setText(QtWidgets.QApplication.translate("GamePatchesWindow", "Add warping to starting location to save stations", None, -1))
        self.warp_to_start_label.setText(QtWidgets.QApplication.translate("GamePatchesWindow", "<html><head/><body><p>Refusing to save at any Save Station will prompt if you want to warp to the starting location (usually Samus\' Ship).</p><p><span style=\" color:#005500;\">Usage of the this option is encouraged for all, as it prevents many softlocks that occurs normally in Echoes.</span></p></body></html>", None, -1))
        self.dark_aether_box.setTitle(QtWidgets.QApplication.translate("GamePatchesWindow", "Dark Aether damage", None, -1))
        self.varia_suit_spin_box.setSuffix(QtWidgets.QApplication.translate("GamePatchesWindow", " energy/s", None, -1))
        self.varia_suit_label.setText(QtWidgets.QApplication.translate("GamePatchesWindow", "Varia Suit", None, -1))
        self.dark_suit_label.setText(QtWidgets.QApplication.translate("GamePatchesWindow", "Dark Suit", None, -1))
        self.dark_suit_spin_box.setSuffix(QtWidgets.QApplication.translate("GamePatchesWindow", " energy/s", None, -1))
        self.dark_aether_label.setText(QtWidgets.QApplication.translate("GamePatchesWindow", "<html><head/><body><p>Configure how much damage per second you take in Dark Aether, per suit.<br/>Light Suit is always imune.</p></body></html>", None, -1))
        self.pickup_style_box.setTitle(QtWidgets.QApplication.translate("GamePatchesWindow", "Pickup style", None, -1))
        self.pickup_model_combo.setItemText(0, QtWidgets.QApplication.translate("GamePatchesWindow", "Use correct item model, scan and name", None, -1))
        self.pickup_model_combo.setItemText(1, QtWidgets.QApplication.translate("GamePatchesWindow", "Use correct scan and name, hide the model", None, -1))
        self.pickup_model_combo.setItemText(2, QtWidgets.QApplication.translate("GamePatchesWindow", "Use correct name, hide the model and scan", None, -1))
        self.pickup_model_combo.setItemText(3, QtWidgets.QApplication.translate("GamePatchesWindow", "Hide the model, scan and name", None, -1))
        self.pickup_data_source_label.setText(QtWidgets.QApplication.translate("GamePatchesWindow", "When hiding some part of the pickup, it\'s replaced with:", None, -1))
        self.pickup_data_source_combo.setItemText(0, QtWidgets.QApplication.translate("GamePatchesWindow", "Energy Transfer Module\'s data", None, -1))
        self.pickup_data_source_combo.setItemText(1, QtWidgets.QApplication.translate("GamePatchesWindow", "A random item data", None, -1))
        self.pickup_data_source_combo.setItemText(2, QtWidgets.QApplication.translate("GamePatchesWindow", "The data of the pickup in that place", None, -1))

