# Generated by Django 2.0.5 on 2018-08-30 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomix_workflows', '0007_workflow_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
