# Generated by Django 2.0.5 on 2019-04-15 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genomix_workflows', '0008_task_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Complete'), (4, 'Hold'), (5, 'Skip'), (6, 'Failed')], default=None, null=True),
        ),
    ]
