# Generated by Django 2.0.5 on 2019-10-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('genomix_workflows', '0010_add_workflow_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowinstance',
            unique_together={('content_type', 'object_id')},
        ),
    ]
