# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-09 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopstarter_data', '0002_auto_20191004_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('validated', 'Validated')], default='pending', verbose_name='Status'),
        ),
    ]
