[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml"


[tool.poetry]
name = "django-split-settings"
version = "1.0.0"
description = "Organize Django settings into multiple files and directories. Easily override and modify settings. Use wildcards and optional settings files."
authors = [
  "sobolevn <mail@sobolevn.me>",
  "Visa Kopu",
  "Antti Kaihola",
]
license = "BSD-2-Clause"
packages = [
  { include = "split_settings" }
]

readme = "README.md"

repository = "https://github.com/sobolevn/django-split-settings"
homepage = "https://django-split-settings.readthedocs.io"

keywords = [
  "django",
  "settings",
  "configuration",
  "config",
]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Web Environment",
  "Framework :: Django",
  "Framework :: Django :: 1.11",
  "Framework :: Django :: 2.1",
  "Framework :: Django :: 2.2",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]


[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
django = "^2.2"

mypy = "^0.730"
wemake-python-styleguide = "^0.12.5"
flake8-pytest = "^1.3"
flake8-pytest-style = "^0.1.3"
nitpick = "^0.21.1"

safety = "^1.8"

pytest = "^5.2"
pytest-cov = "^2.7"
pytest-randomly = "^3.0"

sphinx = "^2.1"
sphinx-autodoc-typehints = "^1.8"
doc8 = "^0.8.0"
tomlkit = "^0.5.4"
m2r = "^0.2"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
