
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-09T16:02:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d217af1f9002aa671f8a3260a687c540ca5336d",
 "version": "0.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
