#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['wtk']

package_data = \
{'': ['*']}

install_requires = \
['Cython', 'POT', 'numpy', 'scikit-learn']

setup(name='wtk',
      version='0.2.1',
      description='A Wasserstein Subsequence Kernel for Time Series',
      author='Christian Bock',
      author_email='christian.bock@bsse.ethz.ch',
      url='https://github.com/BorgwardtLab/WTK',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.6',
     )
