
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-11T14:17:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "553585527d02a6640b9ca25b12e689ff0fe65028",
 "version": "0.3.0.dev0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
