course-id: capp30121-aut-18
course-name: Computer Science with Applications I
quarter: Autumn
year: 2018
gitlab-hostname: mit.cs.uchicago.edu
gitlab-ssl: true
gitlab-group: capp30121-aut-18
gitlab-upstream-repo: capp30121-aut-18
chisubmit-init: true
chisubmit-course: capp30121-aut-18
bashrc-lines:
  - export PYTHONPATH={repo_path}/lib:$PYTHONPATH
