course-id: cs121-aut-15
course-name: Computer Science with Applications I
quarter: Autumn
year: 2015
gitlab-hostname: mit.cs.uchicago.edu
gitlab-ssl: true
gitlab-group: cs121-aut-15
gitlab-upstream-repo: cs121-aut-15
chisubmit-init: true
chisubmit-course: cs121-aut-15
bashrc-lines:
  - export PYTHONPATH={repo_path}/lib:$PYTHONPATH
