course-id: cs121-aut-16
course-name: Computer Science with Applications I
quarter: Autumn
year: 2016
gitlab-hostname: mit.cs.uchicago.edu
gitlab-ssl: true
gitlab-group: cs121-aut-16
gitlab-upstream-repo: cs121-aut-16
chisubmit-init: true
chisubmit-course: cs121-aut-16
bashrc-lines:
  - export PYTHONPATH={repo_path}/lib:$PYTHONPATH
