course-id: cs122-win-17
course-name: Computer Science with Applications II
quarter: Winter
year: 2017
gitlab-hostname: mit.cs.uchicago.edu
gitlab-ssl: true
gitlab-group: cs122-win-17
gitlab-upstream-repo: cs122-win-17
chisubmit-init: true
chisubmit-course: cs122-win-17
bashrc-lines:
  - export PYTHONPATH={repo_path}/lib:$PYTHONPATH
