sudo: false

language: python


python:
    - 3.6
    - 3.7


env:
    - version=minimum  
    - version=latest


before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"


install:
  - if [[ $version == minimum ]]; then pip install matplotlib==3.0.3 numpy==1.16.2 scipy==1.3.0 pandas==0.24.2 lmfit==0.9.13 PyQt5==5.13.0 codecov pysprint;fi
  - if [[ $version == latest ]]; then pip install -r requirements.txt codecov pysprint; fi
  - pip list


script:
  - cd pysprint/tests
  - python test_loading.py
  - python test_edit.py
  - python test_evaluate.py
  - coverage run test_loading.py
  - coverage run test_edit.py
  #- coverage run test_evaluate.py

after_success:
  - codecov