# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2019-08-29 18:08:07 UTC
from __future__ import unicode_literals
import datetime

version = "3.0.2"
githash = "e770fd1ad36928144fc0d4b743b8ddaea294d389"


major = 3
minor = 0
bugfix = 2

release = True
timestamp = datetime.datetime(2019, 8, 29, 18, 8, 7)
debug = False

astropy_helpers_version = ""

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
