[tool.poetry]
name = "z4-solver"
version = "2019.10.12"
description = "z3++"
authors = ["Asger Hautop Drewsen <asgerdrewsen@gmail.com>"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.7"
z3-solver = "^4.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
