#!/usr/bin/env python
from setuptools import setup
setup(name='maniV2',
      version='1.0.0',
      packages=['maniV2'],
      install_requires=['redis',
                        'python-redis-lock',
                        'pytz'],
      setup_requires=['setuptools'],
      tests_require=['flake8'],
      description='Distributed cron',
      author='Aishwat',
      author_email='aishwat.singh@target.com',
      url='https://git.target.com/aishwat/mani.git',
      keywords=['cron', 'distributed', 'redis'],
      package_data={'maniV2.version': ['VERSION']},
      classifiers=['Environment :: Console',
                   'Intended Audience :: Developers',
                   'Operating System :: Unix',
                   'Operating System :: POSIX',
                   'Programming Language :: Python',
                   'Topic :: System',
                   'Topic :: Software Development',
                   'Development Status :: 4 - Beta'])
