language: python
python:
  - "2.7"
  - "3.6"
install:
  - "python setup.py install"
  - "pip install flask_wtf"
  - "pip install pytest-flask"
  - "pip install flake8"
script:
  - "flake8 flask_simplelogin/"
  - "flake8 example/"
  - "flake8 tests/"
  - "py.test -v tests/"
