language: python

matrix:
  include:
    - sudo: required
      language: python
      python: 3.6
      services:
        - docker
      env:
        CIBW_SKIP="*-manylinux1_i686"
        CIBW_MANYLINUX1_X86_64_IMAGE="quay.io/wenxiang/kafka-cffi-manylinux-builder"

install:
  - pip install twine cibuildwheel

script:
  - docker run --user $(id -u):$(id -g) --rm -w /app -v $PWD:/app
    quay.io/wenxiang/kafka-cffi-pypy-builder scripts/build-wheels.sh
  - cibuildwheel --output-dir wheelhouse
  - python setup.py sdist
  - ls -la wheelhouse/*.whl pypy-wheelhouse/*.whl dist/*.tar.gz
  - wheel_versions=($(ls -1 wheelhouse/*.whl pypy-wheelhouse/*.whl |
                       sed -re 's/.*kafka_cffi-([^-]+)-(pp|cp)[0-9]+.*/\1/' |
                       sort -u))
  - if [[ ${#wheel_versions[@]} -gt 1 ]]; then
      echo "Multiple wheel versions found (${wheel_versions[@]}). Aborting upload to pypi";
      false;
    elif [[ ! $(python setup.py --version) =~ dev ]]; then
      echo "Not a dev version, uploading to pypi" &&
      twine upload dist/*.tar.gz wheelhouse/*.whl pypy-wheelhouse/*.whl;
    else
      echo "Dev version, skipping upload";
    fi
