
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-08T14:21:27+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "3cdf1b6a7b824cf09d9ac20067384a8cc1484cfc",
 "version": "1.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
