"""
Django settings for ambition_metadata_rules project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ETC_DIR = os.path.join(BASE_DIR, "etc")
SITE_ID = 40
REVIEWER_SITE_ID = 0

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "yvnesm+cu1f)0oesr0hndkq2r^7u#wq_a3g%cfuagn5vq!&j&q"
APP_NAME = "ambition_metadata_rules"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django_crypto_fields.apps.AppConfig",
    "django_revision.apps.AppConfig",
    "edc_action_item.apps.AppConfig",
    "edc_appointment.apps.AppConfig",
    "edc_lab.apps.AppConfig",
    "edc_visit_tracking.apps.AppConfig",
    "edc_visit_schedule.apps.AppConfig",
    "edc_identifier.apps.AppConfig",
    "edc_device.apps.AppConfig",
    "edc_offstudy.apps.AppConfig",
    "edc_protocol.apps.AppConfig",
    "edc_registration.apps.AppConfig",
    "edc_reference.apps.AppConfig",
    "edc_metadata_rules.apps.AppConfig",
    "edc_notification.apps.AppConfig",
    "ambition_labs.apps.AppConfig",
    "ambition_lists.apps.AppConfig",
    "ambition_reference.apps.AppConfig",
    "ambition_prn.apps.AppConfig",
    "ambition_rando.apps.AppConfig",
    "ambition_visit_schedule.apps.AppConfig",
    "ambition_screening.apps.AppConfig",
    "ambition_subject.apps.AppConfig",
    "ambition_metadata_rules.apps.EdcFacilityAppConfig",
    "ambition_metadata_rules.apps.EdcMetadataAppConfig",
    "ambition_metadata_rules.apps.AppConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "edc_dashboard.middleware.DashboardMiddleware",
    "edc_subject_dashboard.middleware.DashboardMiddleware",
]

ROOT_URLCONF = "ambition_metadata_rules.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "ambition_metadata_rules.wsgi.application"


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_ROOT = os.path.join(BASE_DIR, "ambition_metadata_rules", "static")
COUNTRY = "botswana"
HOLIDAY_FILE = os.path.join(
    BASE_DIR, "ambition_metadata_rules", "tests", "holidays.csv"
)

STATIC_URL = "/static/"

RANDOMIZATION_LIST_PATH = os.path.join(
    BASE_DIR, "ambition_metadata_rules", "tests", "test_randomization_list.csv"
)

DASHBOARD_URL_NAMES = {
    "subject_models_url": "subject_models_url",
    "subject_listboard_url": "ambition_dashboard:subject_listboard_url",
    "screening_listboard_url": "ambition_dashboard:screening_listboard_url",
    "subject_dashboard_url": "ambition_dashboard:subject_dashboard_url",
}

EMAIL_ENABLED = False
EMAIL_CONTACTS = {}

if "test" in sys.argv:

    class DisableMigrations:
        def __contains__(self, item):
            return True

        def __getitem__(self, item):
            return None

    MIGRATION_MODULES = DisableMigrations()
    PASSWORD_HASHERS = ("django.contrib.auth.hashers.MD5PasswordHasher",)
    DEFAULT_FILE_STORAGE = "inmemorystorage.InMemoryStorage"
