#image: python:3.6-alpine
image: continuumio/miniconda3:latest

stages:
  - test
  - deploy

before_script:
  - pip install pytest
  - pip install twine


test_merge_requests:
  stage: test
  script:
    - conda create -n gitlab_test python=3.6
    - source activate gitlab_test
    - conda install gxx_linux-64
    - pip install pytest
    - python setup.py install
    - pytest tests
  only:
  - merge_requests
  except:
    - tags

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - python setup.py sdist
    - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
  only:
    - tags