# Generated by Django 2.2.5 on 2019-09-19 22:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('cc_email', models.CharField(blank=True, help_text='You can provide an E-Mail address (or multiple using a comma seperated list) to cc all E-Mails sent using this template.', max_length=255, null=True, verbose_name='CC E-Mail')),
                ('bcc_email', models.CharField(blank=True, help_text='You can provide an E-Mail address (or multiple using a comma seperated list) to bcc all E-Mails sent using this template.', max_length=255, null=True, verbose_name='BCC E-Mail')),
                ('content', tinymce.models.HTMLField(help_text='This is the content that will be sent when this template is used.')),
            ],
            options={
                'verbose_name': 'E-Mail Template',
                'verbose_name_plural': 'E-Mail Templates',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_emails', models.CharField(help_text='This can be a list of E-Mails seperated by comma(,).', max_length=255, null=True, verbose_name='Test emails')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
