
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-10T15:11:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f2f41c145c91a502ce06eca4f36dd0c7f537b3bd",
 "version": "3.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
