language: python
sudo: false
dist: trusty
python: "3.6"

cache:
    apt: true
    pip: true
    ccache: true

before_install:
    - pip install -U setuptools pip wheel
    - pip install codecov

install:
    - pip install PyQt5==5.9.2 AnyQt
    - travis_wait pip install -e .
    - pip install git+https://github.com/biolab/orange3.git

script:
    - catchsegv xvfb-run -a -s "-screen 0 1280x1024x24" coverage run setup.py test

after_success:
    - codecov
