# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-02 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopstarter_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='coopstarter_data.Organisation'),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='format',
        ),
        migrations.AddField(
            model_name='resource',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='coopstarter_data.Format'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='coopstarter_data.Language', verbose_name='Language'),
        ),
    ]
