# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coopstarter_data', '0002_auto_20191002_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('code', models.CharField(max_length=2, verbose_name='ISO Code')),
                ('name', models.CharField(max_length=64, verbose_name='Country name')),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'control'),
            },
        ),
        migrations.AlterField(
            model_name='mentor',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coopstarter_data.Country'),
        ),
        migrations.AlterField(
            model_name='request',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coopstarter_data.Country'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coopstarter_data.Country'),
        ),
    ]
