[tool.poetry]
name = "cmft"
version = "0.1.0"
description = ""
license = "MIT"
authors = ["dryobates <jakub.stolarski@gmail.com>"]
readme="README.md"
repository="https://github.com/dryobates/commit-message-from-test"
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Software Development",
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.6"
pytest-flake8 = "^1.0"
pytest-black = { version = "^0.3.3", python = "^3.6" }
black = { version = "^18.9b0", python = "^3.6" }

[tool.poetry.scripts]
cmft = 'cmft.__main__:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
