
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-10T10:57:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "09da309d9fb0cdeda6be9c3c2eea8f5d0c8e5b97",
 "version": "0.1.0a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
