dist: xenial
language: python
cache: false

env:
  global:
    - PYTEST_ADDOPTS=-vv

stages:
  - name: test
    if: tag IS NOT present
  - name: release
    if: tag IS present

jobs:
  include:
    - python: 'pypy2.7-6.0'
      env: TOXENV=pypy-coverage
    - python: 'pypy3.5-6.0'
      env: TOXENV=pypy3-coverage
    - python: '3.7'
      env: TOXENV=py37-coverage
    - python: '3.6'
      env: TOXENV=py36-coverage
    - python: '3.5'
      env: TOXENV=py35-coverage
    - python: '3.4'
      env: TOXENV=py34-coverage
    - python: '2.7'
      env: TOXENV=py27-coverage
    - python: '3.8-dev'
      env: TOXENV=py38-coverage

    - python: '3.7'
      env: TOXENV=checkqa

    - stage: release
      python: '3.7'
      script: skip
      install: skip
      deploy:
        provider: pypi
        user: "__token__"
        password:
          secure: "K7aCzKbiKqPhXhueB8OBl+6uu6Z7iQeKBircMmK6Et7oXhAkaQk28lboLBtpVhCEm0D2rWQnhoEVMUKsQ76FdX+kmBzGaQw4sU7v41gDo3IyD/oozoWeni26GRjWNbznulOd8SE9n2qjSXNihDAeWDFLELPNulvLWfmB/hCR8d8XHurZSmbV1Wu/553ULAMCmjowZLMskR5Y2HjdIkGdTzj3lCLcMdstWS3bxvq8YpJRM8KOGWs9I2D1dac2M5IrDDVmlG+0scvn9cqilB4vGEZm+HsWLHJvQBJ6J7GaQBVI2KcHiytu2fwcvXxSdJXB/Rx2WftwWnb0tAQQ0/I0CmgCBwn8y8cPmTAQ6QP1wlXl8LLYIzuzki1PSGYmWSo0Ztg6Zwls5EqOOiSspCAjVwtYZKsA7JLz60GA4FDuoUvT5aJhZ+QF/t5lEsm/QMWke5CxlayzRXU/Y9Yt6WynX+DSEAF8oHV9FIsdxODxp8q92QLMaNIQHMUgIh02Cu/RZ45ImRKUNDTh1h5UE0kla1htAt31V/w43uJGWRNj7lYrt56iR6uikFsgAYwwMOOIBmP95ilRttSAikX/O+AjGgdj1/J95hZtL9lCxCcy6iXlN9Wk/oj59r64wXYKgbU74PHorN2EEZQf3iLkfW7x1L3HZkg05tBkc+bzBluO0Dk="
        on:
          tags: true
          distributions: 'sdist bdist_wheel'
          repo: pdbpp/pdbpp

install:
  - pip install tox-travis

script:
  - tox

after_script:
  - |
    if [[ "$TOXENV" != checkqa ]]; then
      bash <(curl -s https://codecov.io/bash) -Z -X gcov -X coveragepy -X search -X xcode -X gcovout -X fix -f coverage.xml -n ${TRAVIS_PYTHON_VERSION}
    fi

branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
