---
general:
    logging:
        level: INFO
    outdir: .

observations:
    datastore: $GAMMAPY_DATA/hess-dl3-dr1
    filters:
        - filter_type: all

datasets:
    dataset-type: not assigned
    stack-datasets: true
    geom:
        region: {}
        axes: []

fit:
    fit_range: {}

flux-points: {}
