[tool.poetry]
name = "yappa"
version = "0.2.0"
description = ""
authors = ["Mike <mikhail.g.novikov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.9"
python-slugify = "^3.0"
flask = "^1.1"
click = "^7.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
yappa = 'yappa.cli:cli'


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
