language: python
dist: bionic
python:
- '2.7'
- '3.6'
- 3.7-dev
- 3.8-dev
install:
- pip install codecov
- pip install -r requirements.txt
- pip install -r test_requirements.txt
script: python setup.py test
after_success:
- codecov -t 49bda5c1-5415-4836-9ddf-00165c853924
deploy:
  provider: pypi
  user: russtorres
  password:
    secure: VJkbsOs4xNCewisQOxb5mMvYpvib6hU0PYjOvFcN2RU44QutjtuqSUuyvogHrNk40SSmM10REQA+oDcHdP/WIKcPz0a+JFqqRTVeB4/xjqpq3wkKfMf7vZH7Nd0+Klu7UU57ZYagRHYIYMWI0jXJDkeauJfBUGKLDHkZl94TxPVylAJLMHuyPZtD4k+Bj5jVNvdo7mZ741T8MEeruHWZBgbaO2D4qjGvuzlLa05Qq9MmoQNU1OWzL6cvIfz/uNkguBaChxEYHmumHzAmu5+a3fE07Py3BGEtphTxhvVmP5Q2PrN7m2N8YB1yRpIGEJAfxlw2CGyfWpyG1CduKXBUbG1u011Xs8IY7laKt1Y16WydHZ2BR16XZxY6pVXcPibnqkAb8sLyKk1k7ZvlOOViM8kohp7jNp1Bgdk2neN1OzCbIUp97Op7FKsagsFPy9lw956XXhcrnvdbYy19wS2d+F9NVW9Oesxmc+Q8oiPNh5Y2ugAIwqaTm+kbeQch/0bfAV1R5+V5avBtUgrKOo5y+q8D4TlmYPKjXVE9FuAQcMPoj7FW1toKx/MaSfNeSefvOJh6XaoRkMmwQPXTrKeZLRZO4I4U9oB943fV38A4302lKtApyaUjB0YVfO2aq+XaqvRT38Mkw/m9S54TmyP1TCh2kNti+JlebEtc5qmgd2Y=
  on:
    tags: true
