
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-06T01:40:58-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "dae7d734076966380ec36e867489a53afc89a93e",
 "version": "0+untagged.565.gdae7d73.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
