# coding: utf-8

"""
    Octopus Energy

    This is a representation of the Octopus Energy [REST API](https://developer.octopus.energy/docs/api/)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ExtraProductSampleConsumptionDualFuelSingleRate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'electricity_standard': 'int',
        'gas_standard': 'int'
    }

    attribute_map = {
        'electricity_standard': 'electricity_standard',
        'gas_standard': 'gas_standard'
    }

    def __init__(self, electricity_standard=None, gas_standard=None):  # noqa: E501
        """ExtraProductSampleConsumptionDualFuelSingleRate - a model defined in Swagger"""  # noqa: E501

        self._electricity_standard = None
        self._gas_standard = None
        self.discriminator = None

        if electricity_standard is not None:
            self.electricity_standard = electricity_standard
        if gas_standard is not None:
            self.gas_standard = gas_standard

    @property
    def electricity_standard(self):
        """Gets the electricity_standard of this ExtraProductSampleConsumptionDualFuelSingleRate.  # noqa: E501


        :return: The electricity_standard of this ExtraProductSampleConsumptionDualFuelSingleRate.  # noqa: E501
        :rtype: int
        """
        return self._electricity_standard

    @electricity_standard.setter
    def electricity_standard(self, electricity_standard):
        """Sets the electricity_standard of this ExtraProductSampleConsumptionDualFuelSingleRate.


        :param electricity_standard: The electricity_standard of this ExtraProductSampleConsumptionDualFuelSingleRate.  # noqa: E501
        :type: int
        """

        self._electricity_standard = electricity_standard

    @property
    def gas_standard(self):
        """Gets the gas_standard of this ExtraProductSampleConsumptionDualFuelSingleRate.  # noqa: E501


        :return: The gas_standard of this ExtraProductSampleConsumptionDualFuelSingleRate.  # noqa: E501
        :rtype: int
        """
        return self._gas_standard

    @gas_standard.setter
    def gas_standard(self, gas_standard):
        """Sets the gas_standard of this ExtraProductSampleConsumptionDualFuelSingleRate.


        :param gas_standard: The gas_standard of this ExtraProductSampleConsumptionDualFuelSingleRate.  # noqa: E501
        :type: int
        """

        self._gas_standard = gas_standard

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExtraProductSampleConsumptionDualFuelSingleRate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
