# coding: utf-8

"""
    Octopus Energy

    This is a representation of the Octopus Energy [REST API](https://developer.octopus.energy/docs/api/)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.partial_tariff import PartialTariff  # noqa: F401,E501


class FullTariff(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'direct_debit_monthly': 'PartialTariff',
        'direct_debit_quarterly': 'PartialTariff'
    }

    attribute_map = {
        'direct_debit_monthly': 'direct_debit_monthly',
        'direct_debit_quarterly': 'direct_debit_quarterly'
    }

    def __init__(self, direct_debit_monthly=None, direct_debit_quarterly=None):  # noqa: E501
        """FullTariff - a model defined in Swagger"""  # noqa: E501

        self._direct_debit_monthly = None
        self._direct_debit_quarterly = None
        self.discriminator = None

        if direct_debit_monthly is not None:
            self.direct_debit_monthly = direct_debit_monthly
        if direct_debit_quarterly is not None:
            self.direct_debit_quarterly = direct_debit_quarterly

    @property
    def direct_debit_monthly(self):
        """Gets the direct_debit_monthly of this FullTariff.  # noqa: E501


        :return: The direct_debit_monthly of this FullTariff.  # noqa: E501
        :rtype: PartialTariff
        """
        return self._direct_debit_monthly

    @direct_debit_monthly.setter
    def direct_debit_monthly(self, direct_debit_monthly):
        """Sets the direct_debit_monthly of this FullTariff.


        :param direct_debit_monthly: The direct_debit_monthly of this FullTariff.  # noqa: E501
        :type: PartialTariff
        """

        self._direct_debit_monthly = direct_debit_monthly

    @property
    def direct_debit_quarterly(self):
        """Gets the direct_debit_quarterly of this FullTariff.  # noqa: E501


        :return: The direct_debit_quarterly of this FullTariff.  # noqa: E501
        :rtype: PartialTariff
        """
        return self._direct_debit_quarterly

    @direct_debit_quarterly.setter
    def direct_debit_quarterly(self, direct_debit_quarterly):
        """Sets the direct_debit_quarterly of this FullTariff.


        :param direct_debit_quarterly: The direct_debit_quarterly of this FullTariff.  # noqa: E501
        :type: PartialTariff
        """

        self._direct_debit_quarterly = direct_debit_quarterly

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FullTariff):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
