[tool.poetry]
name = "poetryexample"
version = "0.2.0"
description = ""
authors = ["Alan Bacon <alan.bacon@bbc.co.uk>"]

[tool.poetry.dependencies]
python = "^3.4"
FnF = "^2.0"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
