- project:
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - tempest-plugin-jobs
    check:
      jobs:
        - python-troveclient-tempest-neutron-src
        - trove-tempest-plugin
        - trove-tempest-ipv6-only
    gate:
      queue: trove
      jobs:
        - python-troveclient-tempest-neutron-src
        - trove-tempest-plugin
        - trove-tempest-ipv6-only
- job:
    name: trove-tempest-plugin
    parent: devstack-tempest
    required-projects: &base_required_projects
      - openstack/neutron
      - openstack/trove
      - openstack/trove-tempest-plugin
      - openstack/tempest
    vars: &base_vars
      tox_envlist: all
      devstack_localrc:
        TEMPEST_PLUGINS: /opt/stack/trove-tempest-plugin
      devstack_plugins:
        trove: https://opendev.org/openstack/trove
      devstack_services:
        tempest: true
        tls-proxy: false
      tempest_test_regex: ^trove_tempest_plugin\.tests

- job:
    name: trove-tempest-ipv6-only
    parent: devstack-tempest-ipv6
    description: |
      Trove devstack tempest tests job for IPv6-only deployment
    required-projects: *base_required_projects
    vars: *base_vars
