[tool.poetry]
name = "turmalin"
version = "2.5.1"
description = "A client for APIs written in Flask-Potion"
authors = ["Lars Schöning <lars@lyschoening.de>", "Alexander Lavrov <egnod@ya.ru>"]
license = "MIT"
repository = "https://github.com/biosustain/potion-client"

packages = [

    {include = "potion_client", from = "."}

]



[tool.poetry.dependencies]
python = "^3.7"
jsonschema = "^3.0"
requests = "^2.5"
six = "^1.12"

[tool.poetry.dev-dependencies]
responses = "^0.10.6"
nose = "^1.3"
pre-commit = "^1.18"
bumpversion = "^0.5.3"
coveralls = "^1.8"


[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
  )
)
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
