[tool.poetry]
name = "keios-dynabuffers-rhea"
version = "0.1.0"
description = ""
authors = ["fridayy <benjamin.krenn@leftshift.one>"]
packages = [{include ="keios"}]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
