
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-13T16:51:33-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a86e551984eda3df4689149fa78420929a9561f5",
 "version": "0.0.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
