# Generated by Django 2.0.1 on 2018-11-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohm2_currencies_light', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertionrate',
            name='identity',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='identity',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lastconvertionrate',
            name='identity',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
