# Generated by Django 2.2.5 on 2019-09-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohm2_currencies_light', '0002_auto_20181119_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertionrate',
            name='identity',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='identity',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='lastconvertionrate',
            name='identity',
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
