[tool.poetry]
name = "aws_assume"
version = "0.1.3"
description = "AWS session token refreshing daemon"
authors = ["Dick Marinus <dick@mrns.nl>"]

[tool.poetry.dependencies]
python = "^3.7"
yubikey-manager = "2.1.0"
click = "7.0"
boto3 = "1.9.101"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
_assume = "aws_assume._assume:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
