
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-06T00:15:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8ad660a3bc18d9c4f0109f8797af2e4434797c42",
 "version": "0.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
