
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-26T15:44:04+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "744b16b06e4147d1e281eacab9e892990c58563f",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
