---
# This playbook provisions the openstack topology.

- name:  "schema check and Pre Provisioning Activities on topology_file"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'common' }

- name:  "Provisioning AWS resources"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'aws' }

- name: "Writing contents to file"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'gather_resources' }
