---
# This playbook provisions the google compute engine topology.

- name:  "schema check and Pre Provisioning Activities on topology_file"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'common' }

- name:  "Provisioning google cloud resources"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'gcloud' }

- name: "Writing contents to file"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'gather_resources' }
