---
# This playbook provisions the ovirt topology.

- name:  "schema check and Pre Provisioning Activities on topology_file"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'common' }

- name:  "Provisioning ovirt resources"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'ovirt' }

- name: "Gather resources to the RunDB"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'gather_resources' }
