
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-08T11:30:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "842f0f528fb09f9fff062cb61d49f58c67aa91de",
 "version": "0.10.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
