# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _itkFrequencyExpandImageFilterPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkFrequencyExpandImageFilterPython', [dirname(__file__)])
        except ImportError:
            import _itkFrequencyExpandImageFilterPython
            return _itkFrequencyExpandImageFilterPython
        if fp is not None:
            try:
                _mod = imp.load_module('_itkFrequencyExpandImageFilterPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _itkFrequencyExpandImageFilterPython = swig_import_helper()
    del swig_import_helper
else:
    import _itkFrequencyExpandImageFilterPython
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import ITKCommonBasePython
import pyBasePython
import itkFixedArrayPython
import itkImageToImageFilterAPython
import itkImageSourcePython
import itkImageSourceCommonPython
import itkImagePython
import itkRGBAPixelPython
import itkOffsetPython
import itkSizePython
import itkRGBPixelPython
import itkCovariantVectorPython
import vnl_vectorPython
import stdcomplexPython
import vnl_matrixPython
import itkVectorPython
import vnl_vector_refPython
import itkMatrixPython
import vnl_matrix_fixedPython
import itkPointPython
import itkSymmetricSecondRankTensorPython
import itkImageRegionPython
import itkIndexPython
import itkVectorImagePython
import itkVariableLengthVectorPython
import itkImageToImageFilterCommonPython

def itkFrequencyExpandImageFilterIF3_New():
  return itkFrequencyExpandImageFilterIF3.New()


def itkFrequencyExpandImageFilterIF2_New():
  return itkFrequencyExpandImageFilterIF2.New()

class itkFrequencyExpandImageFilterIF2(itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    """Proxy of C++ itkFrequencyExpandImageFilterIF2 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkFrequencyExpandImageFilterIF2_Pointer":
        """__New_orig__() -> itkFrequencyExpandImageFilterIF2_Pointer"""
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkFrequencyExpandImageFilterIF2_Pointer":
        """Clone(itkFrequencyExpandImageFilterIF2 self) -> itkFrequencyExpandImageFilterIF2_Pointer"""
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_Clone(self)


    def SetExpandFactors(self, *args) -> "void":
        """
        SetExpandFactors(itkFrequencyExpandImageFilterIF2 self, itkFixedArrayUI2 _arg)
        SetExpandFactors(itkFrequencyExpandImageFilterIF2 self, unsigned int const factor)
        """
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_SetExpandFactors(self, *args)


    def GetExpandFactors(self) -> "itkFixedArrayUI2 const &":
        """GetExpandFactors(itkFrequencyExpandImageFilterIF2 self) -> itkFixedArrayUI2"""
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_GetExpandFactors(self)


    def GenerateOutputInformation(self) -> "void":
        """GenerateOutputInformation(itkFrequencyExpandImageFilterIF2 self)"""
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_GenerateOutputInformation(self)


    def GenerateInputRequestedRegion(self) -> "void":
        """GenerateInputRequestedRegion(itkFrequencyExpandImageFilterIF2 self)"""
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_GenerateInputRequestedRegion(self)

    ImageTypeHasNumericTraitsCheck = _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_ImageTypeHasNumericTraitsCheck
    __swig_destroy__ = _itkFrequencyExpandImageFilterPython.delete_itkFrequencyExpandImageFilterIF2

    def cast(obj: 'itkLightObject') -> "itkFrequencyExpandImageFilterIF2 *":
        """cast(itkLightObject obj) -> itkFrequencyExpandImageFilterIF2"""
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkFrequencyExpandImageFilterIF2

        Create a new object of the class itkFrequencyExpandImageFilterIF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkFrequencyExpandImageFilterIF2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkFrequencyExpandImageFilterIF2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkFrequencyExpandImageFilterIF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkFrequencyExpandImageFilterIF2.Clone = new_instancemethod(_itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_Clone, None, itkFrequencyExpandImageFilterIF2)
itkFrequencyExpandImageFilterIF2.SetExpandFactors = new_instancemethod(_itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_SetExpandFactors, None, itkFrequencyExpandImageFilterIF2)
itkFrequencyExpandImageFilterIF2.GetExpandFactors = new_instancemethod(_itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_GetExpandFactors, None, itkFrequencyExpandImageFilterIF2)
itkFrequencyExpandImageFilterIF2.GenerateOutputInformation = new_instancemethod(_itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_GenerateOutputInformation, None, itkFrequencyExpandImageFilterIF2)
itkFrequencyExpandImageFilterIF2.GenerateInputRequestedRegion = new_instancemethod(_itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_GenerateInputRequestedRegion, None, itkFrequencyExpandImageFilterIF2)
itkFrequencyExpandImageFilterIF2_swigregister = _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_swigregister
itkFrequencyExpandImageFilterIF2_swigregister(itkFrequencyExpandImageFilterIF2)

def itkFrequencyExpandImageFilterIF2___New_orig__() -> "itkFrequencyExpandImageFilterIF2_Pointer":
    """itkFrequencyExpandImageFilterIF2___New_orig__() -> itkFrequencyExpandImageFilterIF2_Pointer"""
    return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2___New_orig__()

def itkFrequencyExpandImageFilterIF2_cast(obj: 'itkLightObject') -> "itkFrequencyExpandImageFilterIF2 *":
    """itkFrequencyExpandImageFilterIF2_cast(itkLightObject obj) -> itkFrequencyExpandImageFilterIF2"""
    return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF2_cast(obj)

class itkFrequencyExpandImageFilterIF3(itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    """Proxy of C++ itkFrequencyExpandImageFilterIF3 class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkFrequencyExpandImageFilterIF3_Pointer":
        """__New_orig__() -> itkFrequencyExpandImageFilterIF3_Pointer"""
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkFrequencyExpandImageFilterIF3_Pointer":
        """Clone(itkFrequencyExpandImageFilterIF3 self) -> itkFrequencyExpandImageFilterIF3_Pointer"""
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_Clone(self)


    def SetExpandFactors(self, *args) -> "void":
        """
        SetExpandFactors(itkFrequencyExpandImageFilterIF3 self, itkFixedArrayUI3 _arg)
        SetExpandFactors(itkFrequencyExpandImageFilterIF3 self, unsigned int const factor)
        """
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_SetExpandFactors(self, *args)


    def GetExpandFactors(self) -> "itkFixedArrayUI3 const &":
        """GetExpandFactors(itkFrequencyExpandImageFilterIF3 self) -> itkFixedArrayUI3"""
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_GetExpandFactors(self)


    def GenerateOutputInformation(self) -> "void":
        """GenerateOutputInformation(itkFrequencyExpandImageFilterIF3 self)"""
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_GenerateOutputInformation(self)


    def GenerateInputRequestedRegion(self) -> "void":
        """GenerateInputRequestedRegion(itkFrequencyExpandImageFilterIF3 self)"""
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_GenerateInputRequestedRegion(self)

    ImageTypeHasNumericTraitsCheck = _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_ImageTypeHasNumericTraitsCheck
    __swig_destroy__ = _itkFrequencyExpandImageFilterPython.delete_itkFrequencyExpandImageFilterIF3

    def cast(obj: 'itkLightObject') -> "itkFrequencyExpandImageFilterIF3 *":
        """cast(itkLightObject obj) -> itkFrequencyExpandImageFilterIF3"""
        return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_cast(obj)

    cast = staticmethod(cast)

    def New(*args, **kargs):
        """New() -> itkFrequencyExpandImageFilterIF3

        Create a new object of the class itkFrequencyExpandImageFilterIF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkFrequencyExpandImageFilterIF3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkFrequencyExpandImageFilterIF3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkFrequencyExpandImageFilterIF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkFrequencyExpandImageFilterIF3.Clone = new_instancemethod(_itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_Clone, None, itkFrequencyExpandImageFilterIF3)
itkFrequencyExpandImageFilterIF3.SetExpandFactors = new_instancemethod(_itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_SetExpandFactors, None, itkFrequencyExpandImageFilterIF3)
itkFrequencyExpandImageFilterIF3.GetExpandFactors = new_instancemethod(_itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_GetExpandFactors, None, itkFrequencyExpandImageFilterIF3)
itkFrequencyExpandImageFilterIF3.GenerateOutputInformation = new_instancemethod(_itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_GenerateOutputInformation, None, itkFrequencyExpandImageFilterIF3)
itkFrequencyExpandImageFilterIF3.GenerateInputRequestedRegion = new_instancemethod(_itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_GenerateInputRequestedRegion, None, itkFrequencyExpandImageFilterIF3)
itkFrequencyExpandImageFilterIF3_swigregister = _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_swigregister
itkFrequencyExpandImageFilterIF3_swigregister(itkFrequencyExpandImageFilterIF3)

def itkFrequencyExpandImageFilterIF3___New_orig__() -> "itkFrequencyExpandImageFilterIF3_Pointer":
    """itkFrequencyExpandImageFilterIF3___New_orig__() -> itkFrequencyExpandImageFilterIF3_Pointer"""
    return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3___New_orig__()

def itkFrequencyExpandImageFilterIF3_cast(obj: 'itkLightObject') -> "itkFrequencyExpandImageFilterIF3 *":
    """itkFrequencyExpandImageFilterIF3_cast(itkLightObject obj) -> itkFrequencyExpandImageFilterIF3"""
    return _itkFrequencyExpandImageFilterPython.itkFrequencyExpandImageFilterIF3_cast(obj)


def frequency_expand_image_filter(*args, **kwargs):
    """Procedural interface for FrequencyExpandImageFilter"""
    import itk
    instance = itk.FrequencyExpandImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def frequency_expand_image_filter_init_docstring():
    import itk
    import itkTemplate
    if isinstance(itk.FrequencyExpandImageFilter, itkTemplate.itkTemplate):
        frequency_expand_image_filter.__doc__ = itk.FrequencyExpandImageFilter.values()[0].__doc__
    else:
        frequency_expand_image_filter.__doc__ = itk.FrequencyExpandImageFilter.__doc__




