# coding: utf-8

"""
    ConfigTree API

    ConfigTree API definitions  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from ct_python.models.application import Application  # noqa: F401,E501
from ct_python.models.organization_group import OrganizationGroup  # noqa: F401,E501


class ParentOrganization(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'organization_slug': 'str',
        'created_at': 'str',
        'last_updated_at': 'str',
        'created_by': 'str',
        'last_updated_by': 'str',
        'groups': 'list[OrganizationGroup]',
        'applications': 'list[Application]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'organization_slug': 'organizationSlug',
        'created_at': 'createdAt',
        'last_updated_at': 'lastUpdatedAt',
        'created_by': 'createdBy',
        'last_updated_by': 'lastUpdatedBy',
        'groups': 'groups',
        'applications': 'applications'
    }

    def __init__(self, id=None, name=None, organization_slug=None, created_at=None, last_updated_at=None, created_by=None, last_updated_by=None, groups=None, applications=None):  # noqa: E501
        """ParentOrganization - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._organization_slug = None
        self._created_at = None
        self._last_updated_at = None
        self._created_by = None
        self._last_updated_by = None
        self._groups = None
        self._applications = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.name = name
        if organization_slug is not None:
            self.organization_slug = organization_slug
        if created_at is not None:
            self.created_at = created_at
        if last_updated_at is not None:
            self.last_updated_at = last_updated_at
        if created_by is not None:
            self.created_by = created_by
        if last_updated_by is not None:
            self.last_updated_by = last_updated_by
        if groups is not None:
            self.groups = groups
        if applications is not None:
            self.applications = applications

    @property
    def id(self):
        """Gets the id of this ParentOrganization.  # noqa: E501


        :return: The id of this ParentOrganization.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ParentOrganization.


        :param id: The id of this ParentOrganization.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ParentOrganization.  # noqa: E501


        :return: The name of this ParentOrganization.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ParentOrganization.


        :param name: The name of this ParentOrganization.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def organization_slug(self):
        """Gets the organization_slug of this ParentOrganization.  # noqa: E501

        The name in all lowercase, suitable for URL identification  # noqa: E501

        :return: The organization_slug of this ParentOrganization.  # noqa: E501
        :rtype: str
        """
        return self._organization_slug

    @organization_slug.setter
    def organization_slug(self, organization_slug):
        """Sets the organization_slug of this ParentOrganization.

        The name in all lowercase, suitable for URL identification  # noqa: E501

        :param organization_slug: The organization_slug of this ParentOrganization.  # noqa: E501
        :type: str
        """

        self._organization_slug = organization_slug

    @property
    def created_at(self):
        """Gets the created_at of this ParentOrganization.  # noqa: E501


        :return: The created_at of this ParentOrganization.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ParentOrganization.


        :param created_at: The created_at of this ParentOrganization.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def last_updated_at(self):
        """Gets the last_updated_at of this ParentOrganization.  # noqa: E501


        :return: The last_updated_at of this ParentOrganization.  # noqa: E501
        :rtype: str
        """
        return self._last_updated_at

    @last_updated_at.setter
    def last_updated_at(self, last_updated_at):
        """Sets the last_updated_at of this ParentOrganization.


        :param last_updated_at: The last_updated_at of this ParentOrganization.  # noqa: E501
        :type: str
        """

        self._last_updated_at = last_updated_at

    @property
    def created_by(self):
        """Gets the created_by of this ParentOrganization.  # noqa: E501


        :return: The created_by of this ParentOrganization.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this ParentOrganization.


        :param created_by: The created_by of this ParentOrganization.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def last_updated_by(self):
        """Gets the last_updated_by of this ParentOrganization.  # noqa: E501


        :return: The last_updated_by of this ParentOrganization.  # noqa: E501
        :rtype: str
        """
        return self._last_updated_by

    @last_updated_by.setter
    def last_updated_by(self, last_updated_by):
        """Sets the last_updated_by of this ParentOrganization.


        :param last_updated_by: The last_updated_by of this ParentOrganization.  # noqa: E501
        :type: str
        """

        self._last_updated_by = last_updated_by

    @property
    def groups(self):
        """Gets the groups of this ParentOrganization.  # noqa: E501


        :return: The groups of this ParentOrganization.  # noqa: E501
        :rtype: list[OrganizationGroup]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this ParentOrganization.


        :param groups: The groups of this ParentOrganization.  # noqa: E501
        :type: list[OrganizationGroup]
        """

        self._groups = groups

    @property
    def applications(self):
        """Gets the applications of this ParentOrganization.  # noqa: E501


        :return: The applications of this ParentOrganization.  # noqa: E501
        :rtype: list[Application]
        """
        return self._applications

    @applications.setter
    def applications(self, applications):
        """Sets the applications of this ParentOrganization.


        :param applications: The applications of this ParentOrganization.  # noqa: E501
        :type: list[Application]
        """

        self._applications = applications

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ParentOrganization, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ParentOrganization):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
