
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-01T14:59:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "397362a5a72740460ad2b97425a7ac76a574ce05",
 "version": "0.22.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
