[tool.poetry]
name = "springust"
version = "0.1.0"
description = "springust"
authors = ["Boris Korogvich <b.korogvich@gmail.com>"]

[tool.poetry.scripts]
APPLICATION-NAME = 'springust:main'

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
