# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 14:21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomiq', '0001_initial_1'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snstask',
            index=models.Index(fields=['state', 'visible_after'], name='atomiq_snst_state_c7f457_idx'),
        ),
        migrations.AddIndex(
            model_name='sqstask',
            index=models.Index(fields=['state', 'visible_after'], name='atomiq_sqst_state_6e91d2_idx'),
        ),
        migrations.AddIndex(
            model_name='celerytask',
            index=models.Index(fields=['state', 'visible_after'], name='atomiq_cele_state_dc21c4_idx'),
        ),
    ]
