# Generated by Django 2.2.3 on 2019-07-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atomiq', '0002_auto_20180925_0921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SQSTask',
        ),
    ]
