
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-27T15:49:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c664064cc2bd9382adb410fe3e966bc77128f22d",
 "version": "v0.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
