[tool.poetry]
name = "oracle-version"
version = "0.2.0"
description = "Oracle - until for intresting versions name"
authors = ["Alexander Lavrov <egnod@ya.ru>"]
license = "MIT"

packages = [

    {include="src", from="."}

]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
bumpversion = "^0.5.3"
pre-commit = "^1.18"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
