
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-27T22:46:27-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "35608486fe112563121c422b8fc6f5ca4ee7bea6",
 "version": "2019.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
