---
# vim: set fileencoding=utf-8 :

# connord - connect to nordvpn servers
# Copyright (C) 2019  Mael Stor <maelstor@posteo.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

################################################################################
# config.yml
#
# Configuration for iptables, openvpn and connord. Any variable/dictionary etc.
# defined here can be used in fallback and rules files. Current variables in the
# iptables and openvpn dictionary are just a reasonable default and can be
# adjusted or deleted if not in use.
# ##############################################################################

iptables:
  dns:
    # NordVPN
    - "103.86.99.100/32"
    - "103.86.96.100/32"
  # These variables must be set if you want to use the iptables rules defined in
  # the config directory
  #
  # lan_interface: your_interface_here
  # lan_address: lan_address # with or without cidr of your lan
  # vpn_interface: tun+ # Also available as 'dev' from openvpn environment

openvpn:
  # For an overview of all possible flags see also: `$ man 8 openvpn`. If you
  # want to use --up, --down or any other command that takes scripts see
  # 'scripts' section below. Flags that don't take an argument must be either
  # set to True or False.

  ##### Daemon
  # To see whats going on 'daemon' defaults to False.
  daemon: False

  ##### OpenVPN configuration files
  # If you don't want to use NordVPN or want to stick to a specific
  # configuration you may specify a config here
  # config: /path/to/config.{conf,ovpn}

  ##### Authentication
  # May be 'built-in' to use connord's credentials file or specify one of your
  # own with an absolute path. If switched off it may be useful to set
  # auth-nocache to False or else openvpn may ask you multiple times for your
  # credentials.
  auth-user-pass: "built-in"
  # Don't cache --askpass or --auth-user-pass username/passwords in virtual
  # memory.
  auth-nocache: False
  # type may be one of 'none', 'nointeract', 'interact'
  auth-retry: "nointeract"

  ##### Miscelleanous
  down-pre: True
  redirect-gateway: True

  ##### Scripts
  # This allows scripts to be used during initialization of openvpn
  script-security: 2

  # 'scripts' is special to connord and not found within openvpn documentation.
  # Pass the path to your script or use 'built-in' to use the one from connord.
  # You may comment out a script if you don't want to use a
  # script. If you switch them off take caution not to use variables
  # from these scripts in your rules files. 'stage' may be 'up', 'down',
  # 'always' or 'never' and gives a hint when to check for existence of the file
  # specified with 'creates'. If a script doesn't create anything add an empty
  # string to 'creates'. Created files of built-in scripts can be found in
  # /var/run/connord
  scripts:
    # An example for an own up script
    # - name: 'up'
    #   path: '/path/to/myupscript'
    #   stage: 'up'
    #   creates: ''
    - name: "up"
      path: "built-in"
      stage: "up"
      creates: "up.env"
    - name: "down"
      path: "built-in"
      stage: "down"
      creates: "down.env"
    - name: "ipchange"
      path: "built-in"
      stage: "always"
      creates: "ipchange.env"
