# Generated by Django 2.1.3 on 2018-11-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='value_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
