# Generated by Django 2.2.5 on 2019-09-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DpSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_string', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'dp_settings',
            },
        ),
    ]
