
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-26T18:27:46-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "8b687645c390df775512f28bc718b5746c603133",
 "version": "0+untagged.542.g8b68764.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
