
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-13T18:35:38-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "23c595ebcca28ad1fa09d5536c7f554a4e504a84",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
