# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-04 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopstarter_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.TextField(choices=[('untreated', 'Untreated'), ('dealt-with', 'Dealt With')], default='untreated', verbose_name='Status'),
        ),
    ]
