# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-09 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopstarter_data', '0003_auto_20191009_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated')], default='pending', max_length=32, verbose_name='Status'),
        ),
    ]
