
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-10T21:04:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "86dcea2e7bc4733884a599eb6b95d619f2fc751f",
 "version": "3.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
