[tool.poetry]
name = "beancount-ing-diba"
version = "0.2.1"
description = "Beancount Importer for ING-DiBa (DE) CSV exports"
authors = ["Siddhant Goel <me@sgoel.org>"]
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Plugins",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Financial and Insurance Industry",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3 :: Only",
]
include = ["README.rst", "License.txt"]
repository = "https://github.com/siddhantgoel/beancount-ing-diba"
keywords = ["beancount", "cli-accounting", "finance"]

[tool.black]
line-length = 79
skip-string-normalization = true

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^4.4"
beancount = "^2.2"
black = {version = "^18.3-alpha.0",allows-prereleases = true,python = "^3.6"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
