# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/travis/build/randovania/randovania/randovania/gui/iso_management_window.ui',
# licensing of '/home/travis/build/randovania/randovania/randovania/gui/iso_management_window.ui' applies.
#
# Created: Tue Oct  1 21:04:51 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ISOManagementWindow(object):
    def setupUi(self, ISOManagementWindow):
        ISOManagementWindow.setObjectName("ISOManagementWindow")
        ISOManagementWindow.resize(407, 522)
        self.centralWidget = QtWidgets.QWidget(ISOManagementWindow)
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.current_game_box = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_game_box.sizePolicy().hasHeightForWidth())
        self.current_game_box.setSizePolicy(sizePolicy)
        self.current_game_box.setObjectName("current_game_box")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.current_game_box)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.load_game_button = QtWidgets.QPushButton(self.current_game_box)
        self.load_game_button.setObjectName("load_game_button")
        self.gridLayout_4.addWidget(self.load_game_button, 2, 0, 1, 1)
        self.loaded_game_label = QtWidgets.QLabel(self.current_game_box)
        self.loaded_game_label.setObjectName("loaded_game_label")
        self.gridLayout_4.addWidget(self.loaded_game_label, 1, 0, 1, 3)
        self.clear_game_button = QtWidgets.QPushButton(self.current_game_box)
        self.clear_game_button.setObjectName("clear_game_button")
        self.gridLayout_4.addWidget(self.clear_game_button, 2, 2, 1, 1)
        self.output_folder_label = QtWidgets.QLabel(self.current_game_box)
        self.output_folder_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.output_folder_label.setObjectName("output_folder_label")
        self.gridLayout_4.addWidget(self.output_folder_label, 3, 0, 1, 1)
        self.description_label = QtWidgets.QLabel(self.current_game_box)
        self.description_label.setWordWrap(True)
        self.description_label.setObjectName("description_label")
        self.gridLayout_4.addWidget(self.description_label, 0, 0, 1, 3)
        self.output_folder_button = QtWidgets.QPushButton(self.current_game_box)
        self.output_folder_button.setObjectName("output_folder_button")
        self.gridLayout_4.addWidget(self.output_folder_button, 4, 2, 1, 1)
        self.output_folder_edit = QtWidgets.QLineEdit(self.current_game_box)
        self.output_folder_edit.setObjectName("output_folder_edit")
        self.gridLayout_4.addWidget(self.output_folder_edit, 4, 0, 1, 2)
        self.export_game_button = QtWidgets.QPushButton(self.current_game_box)
        self.export_game_button.setObjectName("export_game_button")
        self.gridLayout_4.addWidget(self.export_game_button, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.current_game_box)
        self.permalink_box = QtWidgets.QGroupBox(self.centralWidget)
        self.permalink_box.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.permalink_box.sizePolicy().hasHeightForWidth())
        self.permalink_box.setSizePolicy(sizePolicy)
        self.permalink_box.setObjectName("permalink_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.permalink_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.permalink_edit = QtWidgets.QLineEdit(self.permalink_box)
        self.permalink_edit.setObjectName("permalink_edit")
        self.gridLayout_5.addWidget(self.permalink_edit, 1, 0, 1, 1)
        self.permalink_import_button = QtWidgets.QPushButton(self.permalink_box)
        self.permalink_import_button.setObjectName("permalink_import_button")
        self.gridLayout_5.addWidget(self.permalink_import_button, 1, 1, 1, 1)
        self.reset_settings_button = QtWidgets.QPushButton(self.permalink_box)
        self.reset_settings_button.setObjectName("reset_settings_button")
        self.gridLayout_5.addWidget(self.reset_settings_button, 2, 0, 1, 2)
        self.seed_number_edit = QtWidgets.QLineEdit(self.permalink_box)
        self.seed_number_edit.setObjectName("seed_number_edit")
        self.gridLayout_5.addWidget(self.seed_number_edit, 0, 0, 1, 1)
        self.seed_number_button = QtWidgets.QPushButton(self.permalink_box)
        self.seed_number_button.setObjectName("seed_number_button")
        self.gridLayout_5.addWidget(self.seed_number_button, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.permalink_box)
        self.rom_output_box = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rom_output_box.sizePolicy().hasHeightForWidth())
        self.rom_output_box.setSizePolicy(sizePolicy)
        self.rom_output_box.setObjectName("rom_output_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.rom_output_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.randomize_and_export_button = QtWidgets.QPushButton(self.rom_output_box)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 255, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 247, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 247, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 255, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 247, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 247, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 255, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 247, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 240, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.randomize_and_export_button.setPalette(palette)
        self.randomize_and_export_button.setAutoFillBackground(True)
        self.randomize_and_export_button.setObjectName("randomize_and_export_button")
        self.gridLayout_3.addWidget(self.randomize_and_export_button, 2, 0, 1, 2)
        self.create_from_log_button = QtWidgets.QPushButton(self.rom_output_box)
        self.create_from_log_button.setObjectName("create_from_log_button")
        self.gridLayout_3.addWidget(self.create_from_log_button, 3, 1, 1, 1)
        self.randomize_log_only_button = QtWidgets.QPushButton(self.rom_output_box)
        self.randomize_log_only_button.setObjectName("randomize_log_only_button")
        self.gridLayout_3.addWidget(self.randomize_log_only_button, 3, 0, 1, 1)
        self.create_spoiler_label = QtWidgets.QLabel(self.rom_output_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_spoiler_label.sizePolicy().hasHeightForWidth())
        self.create_spoiler_label.setSizePolicy(sizePolicy)
        self.create_spoiler_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.create_spoiler_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.create_spoiler_label.setWordWrap(True)
        self.create_spoiler_label.setObjectName("create_spoiler_label")
        self.gridLayout_3.addWidget(self.create_spoiler_label, 1, 0, 1, 2)
        self.create_spoiler_check = QtWidgets.QCheckBox(self.rom_output_box)
        self.create_spoiler_check.setObjectName("create_spoiler_check")
        self.gridLayout_3.addWidget(self.create_spoiler_check, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.rom_output_box)
        ISOManagementWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(ISOManagementWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 407, 21))
        self.menuBar.setObjectName("menuBar")
        ISOManagementWindow.setMenuBar(self.menuBar)

        self.retranslateUi(ISOManagementWindow)
        QtCore.QMetaObject.connectSlotsByName(ISOManagementWindow)

    def retranslateUi(self, ISOManagementWindow):
        ISOManagementWindow.setWindowTitle(QtWidgets.QApplication.translate("ISOManagementWindow", "Hello, world!", None, -1))
        self.current_game_box.setTitle(QtWidgets.QApplication.translate("ISOManagementWindow", "Current Game", None, -1))
        self.load_game_button.setToolTip(QtWidgets.QApplication.translate("ISOManagementWindow", "<html><head/><body><p>Extracts a game ISO for later operations.</p></body></html>", None, -1))
        self.load_game_button.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "Load Game", None, -1))
        self.loaded_game_label.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "This label hasn\'t updated yet. What gives?", None, -1))
        self.clear_game_button.setToolTip(QtWidgets.QApplication.translate("ISOManagementWindow", "<html><head/><body><p>Deletes any previously loaded game. Try this if patching fails for any reason.</p></body></html>", None, -1))
        self.clear_game_button.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "Clear loaded game", None, -1))
        self.output_folder_label.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "Output Folder", None, -1))
        self.description_label.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "Randovania operates on game files extracted to an internal folder. If no games are currently loaded, you must load one before doing anything.", None, -1))
        self.output_folder_button.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "Select Folder", None, -1))
        self.export_game_button.setToolTip(QtWidgets.QApplication.translate("ISOManagementWindow", "<html><head/><body><p>Exports an ISO of the current game. This includes any applied modifications, such as the last seed generation and menu mod.</p></body></html>", None, -1))
        self.export_game_button.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "Export Game", None, -1))
        self.permalink_box.setTitle(QtWidgets.QApplication.translate("ISOManagementWindow", "Permalink", None, -1))
        self.permalink_import_button.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "Import", None, -1))
        self.reset_settings_button.setToolTip(QtWidgets.QApplication.translate("ISOManagementWindow", "<html><head/><body><p>Resets all seed-affecting settings to their default values.</p></body></html>", None, -1))
        self.reset_settings_button.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "Reset Settings", None, -1))
        self.seed_number_edit.setPlaceholderText(QtWidgets.QApplication.translate("ISOManagementWindow", "Random Seed", None, -1))
        self.seed_number_button.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "New Seed", None, -1))
        self.rom_output_box.setTitle(QtWidgets.QApplication.translate("ISOManagementWindow", "ROM Output", None, -1))
        self.randomize_and_export_button.setToolTip(QtWidgets.QApplication.translate("ISOManagementWindow", "<html><head/><body><p>Creates a new seed based on the current settings and then creates an ISO in the output folder.</p></body></html>", None, -1))
        self.randomize_and_export_button.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "Randomize", None, -1))
        self.create_from_log_button.setToolTip(QtWidgets.QApplication.translate("ISOManagementWindow", "<html><head/><body><p>Imports a log file and creates an ISO with the same seed.</p></body></html>", None, -1))
        self.create_from_log_button.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "Create from log file", None, -1))
        self.randomize_log_only_button.setToolTip(QtWidgets.QApplication.translate("ISOManagementWindow", "<html><head/><body><p>Creates a new seed based on the current settings and then exports only it\'s log to the output folder.</p></body></html>", None, -1))
        self.randomize_log_only_button.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "Create only log file", None, -1))
        self.create_spoiler_label.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "<html><head/><body><p>Creates a detailed spoiler file with where each modification to the game documented (item locations, elevator connections, etc) as well as a path you can take to finish the game.</p></body></html>", None, -1))
        self.create_spoiler_check.setText(QtWidgets.QApplication.translate("ISOManagementWindow", "Create Spoiler", None, -1))

