# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/travis/build/randovania/randovania/randovania/gui/seed_details_window.ui',
# licensing of '/home/travis/build/randovania/randovania/randovania/gui/seed_details_window.ui' applies.
#
# Created: Tue Oct  1 21:04:51 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SeedDetailsWindow(object):
    def setupUi(self, SeedDetailsWindow):
        SeedDetailsWindow.setObjectName("SeedDetailsWindow")
        SeedDetailsWindow.resize(852, 607)
        self.centralWidget = QtWidgets.QWidget(SeedDetailsWindow)
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.layout_info_tab = QtWidgets.QTabWidget(self.centralWidget)
        self.layout_info_tab.setObjectName("layout_info_tab")
        self.details_tab = QtWidgets.QWidget()
        self.details_tab.setObjectName("details_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.details_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.layout_trick_text_label = QtWidgets.QLabel(self.details_tab)
        self.layout_trick_text_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layout_trick_text_label.setObjectName("layout_trick_text_label")
        self.gridLayout_4.addWidget(self.layout_trick_text_label, 1, 0, 1, 1)
        self.layout_trick_value_label = QtWidgets.QLabel(self.details_tab)
        self.layout_trick_value_label.setObjectName("layout_trick_value_label")
        self.gridLayout_4.addWidget(self.layout_trick_value_label, 1, 1, 1, 1)
        self.layout_seed_value_label = QtWidgets.QLabel(self.details_tab)
        self.layout_seed_value_label.setObjectName("layout_seed_value_label")
        self.gridLayout_4.addWidget(self.layout_seed_value_label, 0, 1, 1, 1)
        self.layout_elevators_text_label = QtWidgets.QLabel(self.details_tab)
        self.layout_elevators_text_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layout_elevators_text_label.setObjectName("layout_elevators_text_label")
        self.gridLayout_4.addWidget(self.layout_elevators_text_label, 4, 0, 1, 1)
        self.layout_keys_text_label = QtWidgets.QLabel(self.details_tab)
        self.layout_keys_text_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layout_keys_text_label.setObjectName("layout_keys_text_label")
        self.gridLayout_4.addWidget(self.layout_keys_text_label, 2, 0, 1, 1)
        self.layout_seed_text_label = QtWidgets.QLabel(self.details_tab)
        self.layout_seed_text_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layout_seed_text_label.setObjectName("layout_seed_text_label")
        self.gridLayout_4.addWidget(self.layout_seed_text_label, 0, 0, 1, 1)
        self.layout_keys_value_label = QtWidgets.QLabel(self.details_tab)
        self.layout_keys_value_label.setObjectName("layout_keys_value_label")
        self.gridLayout_4.addWidget(self.layout_keys_value_label, 2, 1, 1, 1)
        self.layout_elevators_value_label = QtWidgets.QLabel(self.details_tab)
        self.layout_elevators_value_label.setObjectName("layout_elevators_value_label")
        self.gridLayout_4.addWidget(self.layout_elevators_value_label, 4, 1, 1, 1)
        self.layout_starting_items_text_label = QtWidgets.QLabel(self.details_tab)
        self.layout_starting_items_text_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layout_starting_items_text_label.setObjectName("layout_starting_items_text_label")
        self.gridLayout_4.addWidget(self.layout_starting_items_text_label, 5, 0, 1, 1)
        self.layout_starting_items_value_label = QtWidgets.QLabel(self.details_tab)
        self.layout_starting_items_value_label.setWordWrap(True)
        self.layout_starting_items_value_label.setObjectName("layout_starting_items_value_label")
        self.gridLayout_4.addWidget(self.layout_starting_items_value_label, 5, 1, 1, 1)
        self.layout_info_tab.addTab(self.details_tab, "")
        self.pickup_tab = QtWidgets.QWidget()
        self.pickup_tab.setObjectName("pickup_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pickup_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pickup_spoiler_pickup_combobox = QtWidgets.QComboBox(self.pickup_tab)
        self.pickup_spoiler_pickup_combobox.setObjectName("pickup_spoiler_pickup_combobox")
        self.pickup_spoiler_pickup_combobox.addItem("")
        self.gridLayout_2.addWidget(self.pickup_spoiler_pickup_combobox, 0, 2, 1, 1)
        self.pickup_spoiler_label = QtWidgets.QLabel(self.pickup_tab)
        self.pickup_spoiler_label.setObjectName("pickup_spoiler_label")
        self.gridLayout_2.addWidget(self.pickup_spoiler_label, 0, 0, 1, 1)
        self.pickup_spoiler_scroll_area = QtWidgets.QScrollArea(self.pickup_tab)
        self.pickup_spoiler_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.pickup_spoiler_scroll_area.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.pickup_spoiler_scroll_area.setWidgetResizable(True)
        self.pickup_spoiler_scroll_area.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pickup_spoiler_scroll_area.setObjectName("pickup_spoiler_scroll_area")
        self.pickup_spoiler_scroll_contents = QtWidgets.QWidget()
        self.pickup_spoiler_scroll_contents.setGeometry(QtCore.QRect(0, 0, 796, 493))
        self.pickup_spoiler_scroll_contents.setObjectName("pickup_spoiler_scroll_contents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pickup_spoiler_scroll_contents)
        self.verticalLayout_3.setContentsMargins(3, -1, 3, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pickup_spoiler_scroll_content_layout = QtWidgets.QVBoxLayout()
        self.pickup_spoiler_scroll_content_layout.setObjectName("pickup_spoiler_scroll_content_layout")
        self.verticalLayout_3.addLayout(self.pickup_spoiler_scroll_content_layout)
        self.pickup_spoiler_scroll_area.setWidget(self.pickup_spoiler_scroll_contents)
        self.gridLayout_2.addWidget(self.pickup_spoiler_scroll_area, 2, 0, 1, 3)
        self.pickup_spoiler_show_all_button = QtWidgets.QPushButton(self.pickup_tab)
        self.pickup_spoiler_show_all_button.setObjectName("pickup_spoiler_show_all_button")
        self.gridLayout_2.addWidget(self.pickup_spoiler_show_all_button, 0, 1, 1, 1)
        self.layout_info_tab.addTab(self.pickup_tab, "")
        self.solver_path = QtWidgets.QWidget()
        self.solver_path.setObjectName("solver_path")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.solver_path)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.solver_path_scroll_area = QtWidgets.QScrollArea(self.solver_path)
        self.solver_path_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.solver_path_scroll_area.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.solver_path_scroll_area.setWidgetResizable(True)
        self.solver_path_scroll_area.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.solver_path_scroll_area.setObjectName("solver_path_scroll_area")
        self.solver_path_contents = QtWidgets.QWidget()
        self.solver_path_contents.setGeometry(QtCore.QRect(0, 0, 796, 521))
        self.solver_path_contents.setObjectName("solver_path_contents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.solver_path_contents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.solver_path_content_layout = QtWidgets.QVBoxLayout()
        self.solver_path_content_layout.setObjectName("solver_path_content_layout")
        self.label = QtWidgets.QLabel(self.solver_path_contents)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.solver_path_content_layout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.solver_path_content_layout)
        self.solver_path_scroll_area.setWidget(self.solver_path_contents)
        self.gridLayout_5.addWidget(self.solver_path_scroll_area, 0, 0, 1, 1)
        self.layout_info_tab.addTab(self.solver_path, "")
        self.gridLayout.addWidget(self.layout_info_tab, 0, 0, 3, 1)
        SeedDetailsWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(SeedDetailsWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 852, 21))
        self.menuBar.setObjectName("menuBar")
        SeedDetailsWindow.setMenuBar(self.menuBar)

        self.retranslateUi(SeedDetailsWindow)
        self.layout_info_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SeedDetailsWindow)

    def retranslateUi(self, SeedDetailsWindow):
        SeedDetailsWindow.setWindowTitle(QtWidgets.QApplication.translate("SeedDetailsWindow", "Seed Details", None, -1))
        self.layout_trick_text_label.setText(QtWidgets.QApplication.translate("SeedDetailsWindow", "Trick Level", None, -1))
        self.layout_trick_value_label.setText(QtWidgets.QApplication.translate("SeedDetailsWindow", "layout_trick_value_label", None, -1))
        self.layout_seed_value_label.setText(QtWidgets.QApplication.translate("SeedDetailsWindow", "TextLabel", None, -1))
        self.layout_elevators_text_label.setText(QtWidgets.QApplication.translate("SeedDetailsWindow", "Elevators: ", None, -1))
        self.layout_keys_text_label.setText(QtWidgets.QApplication.translate("SeedDetailsWindow", "Sky Temple Keys:", None, -1))
        self.layout_seed_text_label.setText(QtWidgets.QApplication.translate("SeedDetailsWindow", "Seed:", None, -1))
        self.layout_keys_value_label.setText(QtWidgets.QApplication.translate("SeedDetailsWindow", "TextLabel", None, -1))
        self.layout_elevators_value_label.setText(QtWidgets.QApplication.translate("SeedDetailsWindow", "TextLabel", None, -1))
        self.layout_starting_items_text_label.setText(QtWidgets.QApplication.translate("SeedDetailsWindow", "Starting Items:", None, -1))
        self.layout_starting_items_value_label.setText(QtWidgets.QApplication.translate("SeedDetailsWindow", "TextLabel", None, -1))
        self.layout_info_tab.setTabText(self.layout_info_tab.indexOf(self.details_tab), QtWidgets.QApplication.translate("SeedDetailsWindow", "Configuration", None, -1))
        self.pickup_spoiler_pickup_combobox.setItemText(0, QtWidgets.QApplication.translate("SeedDetailsWindow", "None", None, -1))
        self.pickup_spoiler_label.setToolTip(QtWidgets.QApplication.translate("SeedDetailsWindow", "Enter text to the right to filter the list below", None, -1))
        self.pickup_spoiler_label.setText(QtWidgets.QApplication.translate("SeedDetailsWindow", "Search Pickup", None, -1))
        self.pickup_spoiler_show_all_button.setText(QtWidgets.QApplication.translate("SeedDetailsWindow", "Show All", None, -1))
        self.layout_info_tab.setTabText(self.layout_info_tab.indexOf(self.pickup_tab), QtWidgets.QApplication.translate("SeedDetailsWindow", "Spoiler: Pickups", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("SeedDetailsWindow", "Check the exported log file.", None, -1))
        self.layout_info_tab.setTabText(self.layout_info_tab.indexOf(self.solver_path), QtWidgets.QApplication.translate("SeedDetailsWindow", "Spoiler: Solver Path", None, -1))

