[tool.poetry]
name = "dli-scrapping-lib"
version = "1.0.0"
description = "Open Source Library of all the scrapping python utilities I have used over the years"
authors = ["dli <davidli012345@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22"
beautifulsoup4 = "^4.8"
pandas = "^0.25.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
