
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-04T10:16:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d8411f7338a3a9c71c26f0632f4fd501e1c64ad",
 "version": "v0.8.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
