# Generated by Django 2.2.3 on 2019-09-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_support_lite', '0002_auto_20190920_0716'),
        ('django_support_lite', '0002_auto_20190227_0754'),
    ]

    operations = [
    ]