[tool.poetry]
name = "jrpyvisualisation"
version = "0.1.8"
description = ""
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.5"
plotly = "^4.1"
pandas = "^0.25.0"
numpy = "^1.17"
sklearn = "^0.0.0"
scikit-learn = "^0.21.3"
statsmodels = "^0.10.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
