
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-28T11:13:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "62adda825a5d43e67992847e470bed49dc2834f0",
 "version": "0.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
