####################################################################
# This file is automatically generated
# Do not edit manually
####################################################################

from .BaseWidget import _BaseWidget

from .widgets import Accordion as AccordionOrig
from .widgets import VBox as VBoxOrig
from .widgets import Surface3dVtp as Surface3dVtpOrig
from .widgets import HBox as HBoxOrig
from .widgets import Surface3d as Surface3dOrig
from .widgets import Tabs as TabsOrig



class Accordion(_BaseWidget):
    """Jupyter widget for Accordion"""

    def __init__(self, *args, **kwargs):
        super().__init__(AccordionOrig, 'Accordion', 'ccm_widgets', *args, **kwargs)


class VBox(_BaseWidget):
    """Jupyter widget for VBox"""

    def __init__(self, *args, **kwargs):
        super().__init__(VBoxOrig, 'VBox', 'ccm_widgets', *args, **kwargs)


class Surface3dVtp(_BaseWidget):
    """Jupyter widget for Surface3dVtp"""

    def __init__(self, *args, **kwargs):
        super().__init__(Surface3dVtpOrig, 'Surface3dVtp', 'ccm_widgets', *args, **kwargs)


class HBox(_BaseWidget):
    """Jupyter widget for HBox"""

    def __init__(self, *args, **kwargs):
        super().__init__(HBoxOrig, 'HBox', 'ccm_widgets', *args, **kwargs)


class Surface3d(_BaseWidget):
    """Jupyter widget for Surface3d"""

    def __init__(self, *args, **kwargs):
        super().__init__(Surface3dOrig, 'Surface3d', 'ccm_widgets', *args, **kwargs)


class Tabs(_BaseWidget):
    """Jupyter widget for Tabs"""

    def __init__(self, *args, **kwargs):
        super().__init__(TabsOrig, 'Tabs', 'ccm_widgets', *args, **kwargs)

