# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mnectar/plugins/hashtag/manager.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HashtagManager(object):
    def setupUi(self, HashtagManager):
        HashtagManager.setObjectName("HashtagManager")
        HashtagManager.resize(518, 461)
        self.gridLayout = QtWidgets.QGridLayout(HashtagManager)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(HashtagManager)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(HashtagManager)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 6, 0, 1, 2)
        self.add = QtWidgets.QPushButton(HashtagManager)
        self.add.setAutoDefault(True)
        self.add.setDefault(True)
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 2, 1, 1, 1)
        self.selected_title = QtWidgets.QGroupBox(HashtagManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_title.sizePolicy().hasHeightForWidth())
        self.selected_title.setSizePolicy(sizePolicy)
        self.selected_title.setMinimumSize(QtCore.QSize(0, 105))
        self.selected_title.setMaximumSize(QtCore.QSize(16777215, 105))
        self.selected_title.setAlignment(QtCore.Qt.AlignCenter)
        self.selected_title.setObjectName("selected_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.selected_title)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selected_view = QtWidgets.QListView(self.selected_title)
        self.selected_view.setObjectName("selected_view")
        self.verticalLayout_2.addWidget(self.selected_view)
        self.verticalLayout_2.setStretch(0, 1)
        self.gridLayout.addWidget(self.selected_title, 3, 0, 1, 3)
        self.all = QtWidgets.QListView(HashtagManager)
        self.all.setObjectName("all")
        self.gridLayout.addWidget(self.all, 7, 0, 1, 2)
        self.refresh = QtWidgets.QPushButton(HashtagManager)
        self.refresh.setObjectName("refresh")
        self.gridLayout.addWidget(self.refresh, 8, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(HashtagManager)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(HashtagManager)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.playing = QtWidgets.QRadioButton(self.groupBox)
        self.playing.setObjectName("playing")
        self.verticalLayout.addWidget(self.playing)
        self.selection = QtWidgets.QRadioButton(self.groupBox)
        self.selection.setChecked(True)
        self.selection.setObjectName("selection")
        self.verticalLayout.addWidget(self.selection)
        self.gridLayout.addWidget(self.groupBox, 0, 2, 3, 1)
        self.remove = QtWidgets.QPushButton(HashtagManager)
        self.remove.setAutoDefault(True)
        self.remove.setObjectName("remove")
        self.gridLayout.addWidget(self.remove, 2, 0, 1, 1)
        self.entry = QtWidgets.QLineEdit(HashtagManager)
        self.entry.setClearButtonEnabled(True)
        self.entry.setObjectName("entry")
        self.gridLayout.addWidget(self.entry, 1, 0, 1, 2)
        self.current = QtWidgets.QListView(HashtagManager)
        self.current.setObjectName("current")
        self.gridLayout.addWidget(self.current, 7, 2, 1, 1)
        self.label = QtWidgets.QLabel(HashtagManager)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(HashtagManager)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(7, 1)

        self.retranslateUi(HashtagManager)
        QtCore.QMetaObject.connectSlotsByName(HashtagManager)

    def retranslateUi(self, HashtagManager):
        _translate = QtCore.QCoreApplication.translate
        HashtagManager.setWindowTitle(_translate("HashtagManager", "Form"))
        self.add.setText(_translate("HashtagManager", "Add"))
        self.selected_title.setTitle(_translate("HashtagManager", "Selected"))
        self.refresh.setText(_translate("HashtagManager", "Refresh Tags"))
        self.label_3.setText(_translate("HashtagManager", "<html><head/><body><p><span style=\" font-weight:600;\">All Tags</span></p></body></html>"))
        self.groupBox.setTitle(_translate("HashtagManager", "Target"))
        self.playing.setText(_translate("HashtagManager", "Playing"))
        self.selection.setText(_translate("HashtagManager", "Selection"))
        self.remove.setText(_translate("HashtagManager", "Remove"))
        self.entry.setPlaceholderText(_translate("HashtagManager", "tag list filter / new tag entry"))
        self.label.setText(_translate("HashtagManager", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; text-decoration: underline;\">HashTag Editor</span></p></body></html>"))
        self.label_2.setText(_translate("HashtagManager", "<b>Current Tags</b>"))
