
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-08T15:42:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3286bcf01b7e6bdd1673382b8e28c6bad1e1b8e0",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
