__title__ = 'news2play'
__description__ = 'News for play.'
__url__ = 'http://xxx.xxx'
__version__ = '0.3.9'
__author__ = 'xxx xxx'
__author_email__ = 'xxx@xxx.xxx'
__license__ = 'Apache License, Version 2.0'
__copyright__ = 'Copyright 2019 xxx xxx'
