
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-02T14:52:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c5dd9f5a98d04f63d8034f942f076f3f44b71f7",
 "version": "0.22.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
