# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"

install:
  - pip install tox-travis coveralls pytest-travis-fold
script: tox

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
after_success:
  - coveralls