
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-01T09:27:18-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0bfbee4e692a5cfe4fb6170a9af384b6d8100705",
 "version": "0.2.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
