
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-27T12:27:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b761f645fa4cdd8dba0e6c2291005a235cadc267",
 "version": "1.39.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
