language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - "pip install -U jsonschema"
  - "pip install ."
env:
  - MODEL_TECH=dummy_value
script:
  - "fusesoc init -y"
  - "fusesoc list-cores"
  - "fusesoc update"
  - "py.test"
