[tool.poetry]
name = "solid-mcad"
version = "0.1.1"
description = "Python binding for the OpenSCAD language utility library, MCAD"
authors = ["Evan Jones <evan_t_jones@mac.com>"]

include = [
    "__init__.py",
    "README.md",
    "MCAD/*",
]

[tool.poetry.dependencies]
python = "^3.7"
solidpython=">=0.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
