
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-09T10:01:24+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "7c394df2ff0984b1537fa4efa3ae212b9dce827e",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
