language: python
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8-dev
install:
  - pip install -U setuptools zc.buildout setuptools-scm
  - buildout -n
script:
  - bin/test --cache-clear --cov-report term-missing --cov src
after_success:
cache:
  pip: true
  directories:
    - eggs/
notifications:
  webhooks:
    secure: PuztyZ2thMkwADNPVWaGovrkAfdukZ0d02ENqPYE+sqZzyLraPatjYnV43S+AUKmWNSPD4AIELMoJVeM41aiMKZKuzZabemPcuD1i8kFui5ICH0F00UwBtmyOeArUWuEC/PGnNXCxDiAgIBt8IKuhcXgLLUXcJOdMeOwPAi08r8CZU9oKavXcv3/bIINbd6OkreJB4FnG+b47QzxoaMaaOsPmAzTpGhPkMI/197J+EwGowmre/q+2NAujnkMynbciEYVWZXHWdjrpkPUG9CqmVJTNaZiQoNxgN701D18eMp7GMiGDCQGSJ9VohoBC7adHz0hoMthsQ57+HsfJkApz6pCDKJkLD1gn59N7+7qcuU9j0tE4+WTREbNu1I/D2GSgFx2qnLgGQ7pqJ3Nl7bqpODmXpuG/r9lqWRoWemrcQRZgp7TYnrKofFYddmqPhgyEFt5igo/PjGBsLN6EtfSXs673EUN6bgpImuy4iDT1f/nYpPhAVAYLiGAyu3ZCVgCHF0HpeJcnL4j6oY3pZUNMVbBhj2yvFt1Ze8tlUw7uVGl4dgFVSOUlZFKDH2OsoxDm8T3ecJgJVLw7Iu+8kFZea6p/52Z4pqtCmq42d+O5y8U7ORM8V03ScYMrYoZCfdyYXMwPuHfij3nHj340ULCDfEs9ehhkFRlacIbuZg+myw=
