# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectra_lexer\gui_qt\window\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 470)
        self.w_central = QtWidgets.QWidget(MainWindow)
        self.w_central.setObjectName("w_central")
        self.layout_main = QtWidgets.QGridLayout(self.w_central)
        self.layout_main.setObjectName("layout_main")
        self.w_input = QtWidgets.QLineEdit(self.w_central)
        self.w_input.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_input.sizePolicy().hasHeightForWidth())
        self.w_input.setSizePolicy(sizePolicy)
        self.w_input.setMinimumSize(QtCore.QSize(150, 22))
        self.w_input.setMaximumSize(QtCore.QSize(150, 22))
        self.w_input.setReadOnly(False)
        self.w_input.setObjectName("w_input")
        self.layout_main.addWidget(self.w_input, 0, 0, 1, 1)
        self.w_title = TextTitleWidget(self.w_central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_title.sizePolicy().hasHeightForWidth())
        self.w_title.setSizePolicy(sizePolicy)
        self.w_title.setMinimumSize(QtCore.QSize(0, 22))
        self.w_title.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.w_title.setFont(font)
        self.w_title.setPlaceholderText("")
        self.w_title.setObjectName("w_title")
        self.layout_main.addWidget(self.w_title, 0, 1, 1, 1)
        self.w_matches = SearchListWidget(self.w_central)
        self.w_matches.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_matches.sizePolicy().hasHeightForWidth())
        self.w_matches.setSizePolicy(sizePolicy)
        self.w_matches.setMinimumSize(QtCore.QSize(150, 0))
        self.w_matches.setMaximumSize(QtCore.QSize(150, 16777215))
        self.w_matches.setAutoScroll(False)
        self.w_matches.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.w_matches.setProperty("showDropIndicator", False)
        self.w_matches.setObjectName("w_matches")
        self.layout_main.addWidget(self.w_matches, 1, 0, 1, 1)
        self.w_text = TextGraphWidget(self.w_central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_text.sizePolicy().hasHeightForWidth())
        self.w_text.setSizePolicy(sizePolicy)
        self.w_text.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.w_text.setFont(font)
        self.w_text.setMouseTracking(True)
        self.w_text.setUndoRedoEnabled(False)
        self.w_text.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.w_text.setOpenLinks(False)
        self.w_text.setObjectName("w_text")
        self.layout_main.addWidget(self.w_text, 1, 1, 1, 1)
        self.frame_mappings = QtWidgets.QFrame(self.w_central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_mappings.sizePolicy().hasHeightForWidth())
        self.frame_mappings.setSizePolicy(sizePolicy)
        self.frame_mappings.setMinimumSize(QtCore.QSize(150, 180))
        self.frame_mappings.setMaximumSize(QtCore.QSize(150, 180))
        self.frame_mappings.setObjectName("frame_mappings")
        self.layout_mappings = QtWidgets.QVBoxLayout(self.frame_mappings)
        self.layout_mappings.setContentsMargins(0, 0, 0, 0)
        self.layout_mappings.setObjectName("layout_mappings")
        self.w_mappings = SearchListWidget(self.frame_mappings)
        self.w_mappings.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_mappings.sizePolicy().hasHeightForWidth())
        self.w_mappings.setSizePolicy(sizePolicy)
        self.w_mappings.setMinimumSize(QtCore.QSize(0, 120))
        self.w_mappings.setAutoScroll(False)
        self.w_mappings.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.w_mappings.setProperty("showDropIndicator", False)
        self.w_mappings.setObjectName("w_mappings")
        self.layout_mappings.addWidget(self.w_mappings)
        self.w_strokes = QtWidgets.QCheckBox(self.frame_mappings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_strokes.sizePolicy().hasHeightForWidth())
        self.w_strokes.setSizePolicy(sizePolicy)
        self.w_strokes.setObjectName("w_strokes")
        self.layout_mappings.addWidget(self.w_strokes)
        self.w_regex = QtWidgets.QCheckBox(self.frame_mappings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_regex.sizePolicy().hasHeightForWidth())
        self.w_regex.setSizePolicy(sizePolicy)
        self.w_regex.setObjectName("w_regex")
        self.layout_mappings.addWidget(self.w_regex)
        self.layout_main.addWidget(self.frame_mappings, 2, 0, 1, 1)
        self.frame_info = QtWidgets.QFrame(self.w_central)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_info.sizePolicy().hasHeightForWidth())
        self.frame_info.setSizePolicy(sizePolicy)
        self.frame_info.setMinimumSize(QtCore.QSize(0, 180))
        self.frame_info.setMaximumSize(QtCore.QSize(16777215, 180))
        self.frame_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info.setObjectName("frame_info")
        self.layout_info = QtWidgets.QVBoxLayout(self.frame_info)
        self.layout_info.setContentsMargins(6, 6, 6, 6)
        self.layout_info.setSpacing(2)
        self.layout_info.setObjectName("layout_info")
        self.w_desc = QtWidgets.QLabel(self.frame_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_desc.sizePolicy().hasHeightForWidth())
        self.w_desc.setSizePolicy(sizePolicy)
        self.w_desc.setMinimumSize(QtCore.QSize(0, 0))
        self.w_desc.setMaximumSize(QtCore.QSize(16777215, 64))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.w_desc.setFont(font)
        self.w_desc.setAlignment(QtCore.Qt.AlignCenter)
        self.w_desc.setWordWrap(True)
        self.w_desc.setObjectName("w_desc")
        self.layout_info.addWidget(self.w_desc)
        self.w_board = StenoBoardWidget(self.frame_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_board.sizePolicy().hasHeightForWidth())
        self.w_board.setSizePolicy(sizePolicy)
        self.w_board.setMinimumSize(QtCore.QSize(0, 100))
        self.w_board.setObjectName("w_board")
        self.layout_info.addWidget(self.w_board)
        self.layout_main.addWidget(self.frame_info, 2, 1, 1, 1)
        self.layout_main.setColumnMinimumWidth(0, 150)
        self.layout_main.setColumnMinimumWidth(1, 275)
        self.layout_main.setRowMinimumHeight(0, 22)
        self.layout_main.setRowMinimumHeight(1, 210)
        self.layout_main.setRowMinimumHeight(2, 180)
        MainWindow.setCentralWidget(self.w_central)
        self.w_menu = MainMenu(MainWindow)
        self.w_menu.setGeometry(QtCore.QRect(0, 0, 580, 21))
        self.w_menu.setObjectName("w_menu")
        MainWindow.setMenuBar(self.w_menu)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spectra Lexer"))
        self.w_input.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.w_text.setPlaceholderText(_translate("MainWindow", "Search for any word to see its breakdown."))
        self.w_strokes.setText(_translate("MainWindow", "Stroke Search"))
        self.w_regex.setText(_translate("MainWindow", "Regex Search"))

from .main_menu import MainMenu
from .search_list_widget import SearchListWidget
from .steno_board_widget import StenoBoardWidget
from .text_graph_widget import TextGraphWidget
from .text_title_widget import TextTitleWidget
