- job:
    name: oslo.messaging-tox-py27-func-amqp1
    parent: openstack-tox-py27
    vars:
      tox_envlist: py27-func-amqp1

- job:
    name: oslo.messaging-tox-py27-func-kafka
    parent: openstack-tox-py27
    vars:
      tox_envlist: py27-func-kafka
      bindep_profile: kafka

- job:
    name: oslo.messaging-tox-py27-func-pika
    parent: openstack-tox-py27
    vars:
      tox_envlist: py27-func-pika
      bindep_profile: pika

- job:
    name: oslo.messaging-tox-py27-func-rabbit
    parent: openstack-tox-py27
    vars:
      tox_envlist: py27-func-rabbit
      bindep_profile: rabbit

- job:
    name: oslo.messaging-tox-py27-func-zmq
    parent: openstack-tox-py27
    vars:
      tox_envlist: py27-func-zmq
      bindep_profile: zmq

- job:
    name: oslo.messaging-tox-py27-func-zmq-proxy
    parent: openstack-tox-py27
    vars:
      tox_envlist: py27-func-zmq-proxy
      bindep_profile: zmq

- job:
    name: oslo.messaging-tox-py27-func-zmq-pubsub
    parent: openstack-tox-py27
    vars:
      tox_envlist: py27-func-zmq-pubsub
      bindep_profile: zmq

- job:
    name: oslo.messaging-tox-py35-func-amqp1
    parent: openstack-tox-py35
    vars:
      tox_envlist: py35-func-amqp1

- job:
    name: oslo.messaging-tox-py35-func-rabbit
    parent: openstack-tox-py35
    vars:
      tox_envlist: py35-func-rabbit
      bindep_profile: rabbit

- job:
    name: oslo.messaging-tox-py35-func-zmq
    parent: openstack-tox-py35
    vars:
      tox_envlist: py35-func-zmq
      bindep_profile: zmq

- job:
    name: oslo.messaging-src-dsvm-full-rabbit-default
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-dsvm-full-rabbit-default/run.yaml
    post-run: playbooks/oslo.messaging-src-dsvm-full-rabbit-default/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/oslo.messaging

- job:
    name: oslo.messaging-src-dsvm-full-pika-default
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-dsvm-full-pika-default/run.yaml
    post-run: playbooks/oslo.messaging-src-dsvm-full-pika-default/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-pika
      - openstack/oslo.messaging

- job:
    name: oslo.messaging-src-dsvm-full-amqp1-dual-centos-7
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-dsvm-full-amqp1-dual-centos-7/run.yaml
    post-run: playbooks/oslo.messaging-src-dsvm-full-amqp1-dual-centos-7/post.yaml
    timeout: 10800
    nodeset: legacy-centos-7
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-amqp1
      - openstack/oslo.messaging

- job:
    name: oslo.messaging-src-dsvm-full-amqp1-hybrid
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-dsvm-full-amqp1-hybrid/run.yaml
    post-run: playbooks/oslo.messaging-src-dsvm-full-amqp1-hybrid/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-amqp1
      - openstack/oslo.messaging

- job:
    name: oslo.messaging-src-dsvm-full-kafka-default
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-dsvm-full-kafka-default/run.yaml
    post-run: playbooks/oslo.messaging-src-dsvm-full-kafka-default/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-kafka
      - openstack/oslo.messaging

- job:
    name: oslo.messaging-src-dsvm-full-kafka-default-centos-7
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-dsvm-full-kafka-default-centos-7/run.yaml
    post-run: playbooks/oslo.messaging-src-dsvm-full-kafka-default-centos-7/post.yaml
    timeout: 10800
    nodeset: legacy-centos-7
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-kafka
      - openstack/oslo.messaging

- job:
    name: oslo.messaging-src-dsvm-full-zmq-default
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-dsvm-full-zmq-default/run.yaml
    post-run: playbooks/oslo.messaging-src-dsvm-full-zmq-default/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-zmq
      - openstack/oslo.messaging

- job:
    name: oslo.messaging-src-grenade-dsvm
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-src-grenade-dsvm/run.yaml
    post-run: playbooks/oslo.messaging-src-grenade-dsvm/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/oslo.messaging
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$

- job:
    name: oslo.messaging-src-grenade-dsvm-multinode
    parent: legacy-dsvm-base-multinode
    run: playbooks/oslo.messaging-src-grenade-dsvm-multinode/run.yaml
    post-run: playbooks/oslo.messaging-src-grenade-dsvm-multinode/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/oslo.messaging
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
    nodeset: legacy-ubuntu-xenial-2-node

- job:
    name: oslo.messaging-telemetry-dsvm-integration-amqp1
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-telemetry-dsvm-integration-amqp1/run.yaml
    post-run: playbooks/oslo.messaging-telemetry-dsvm-integration-amqp1/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/devstack-plugin-amqp1
      - openstack/oslo.messaging
      - openstack/panko
      - openstack/telemetry-tempest-plugin
      - openstack/heat-tempest-plugin
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder

- job:
    name: oslo.messaging-telemetry-dsvm-integration-kafka
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-telemetry-dsvm-integration-kafka/run.yaml
    post-run: playbooks/oslo.messaging-telemetry-dsvm-integration-kafka/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/devstack-plugin-kafka
      - openstack/oslo.messaging
      - openstack/panko
      - openstack/telemetry-tempest-plugin
      - openstack/heat-tempest-plugin
      - openstack/heat
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder

- job:
    name: oslo.messaging-telemetry-dsvm-integration-pika
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-telemetry-dsvm-integration-pika/run.yaml
    post-run: playbooks/oslo.messaging-telemetry-dsvm-integration-pika/post.yaml
    timeout: 4200
    required-projects:
      - openstack/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/devstack-plugin-pika
      - openstack/oslo.messaging
      - openstack/panko
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder

- job:
    name: oslo.messaging-telemetry-dsvm-integration-zmq
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-telemetry-dsvm-integration-zmq/run.yaml
    post-run: playbooks/oslo.messaging-telemetry-dsvm-integration-zmq/post.yaml
    timeout: 4200
    required-projects:
      - openstack/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/devstack-plugin-zmq
      - openstack/oslo.messaging
      - openstack/panko
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder

- job:
    name: oslo.messaging-telemetry-dsvm-integration-rabbit
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-telemetry-dsvm-integration-rabbit/run.yaml
    post-run: playbooks/oslo.messaging-telemetry-dsvm-integration-rabbit/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/oslo.messaging
      - openstack/panko
      - openstack/telemetry-tempest-plugin
      - openstack/heat-tempest-plugin
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder

- job:
    name: oslo.messaging-tempest-neutron-dsvm-src-rabbit-default
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-rabbit-default/run.yaml
    post-run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-rabbit-default/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/oslo.messaging
      - openstack/tempest

- job:
    name: oslo.messaging-tempest-neutron-dsvm-src-amqp1-hybrid
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-amqp1-hybrid/run.yaml
    post-run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-amqp1-hybrid/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-amqp1
      - openstack/neutron
      - openstack/oslo.messaging
      - openstack/tempest

- job:
    name: oslo.messaging-tempest-neutron-dsvm-src-kafka-default
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-kafka-default/run.yaml
    post-run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-kafka-default/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-kafka
      - openstack/neutron
      - openstack/oslo.messaging
      - openstack/tempest

- job:
    name: oslo.messaging-tempest-neutron-dsvm-src-pika-default
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-pika-default/run.yaml
    post-run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-pika-default/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-pika
      - openstack/neutron
      - openstack/oslo.messaging
      - openstack/tempest

- job:
    name: oslo.messaging-tempest-neutron-dsvm-src-zmq-default
    parent: legacy-dsvm-base
    run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-zmq-default/run.yaml
    post-run: playbooks/oslo.messaging-tempest-neutron-dsvm-src-zmq-default/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-zmq
      - openstack/neutron
      - openstack/oslo.messaging
      - openstack/tempest


- project:
    name: openstack/oslo.messaging
    check:
      jobs:
        - oslo.messaging-tox-py27-func-amqp1:
            voting: false
        - oslo.messaging-tox-py27-func-kafka:
            voting: false
        - oslo.messaging-tox-py27-func-pika
        - oslo.messaging-tox-py27-func-rabbit
        - oslo.messaging-tox-py27-func-zmq-proxy:
            voting: false
        - oslo.messaging-tox-py27-func-zmq-pubsub:
            voting: false
        - oslo.messaging-tox-py27-func-zmq:
            voting: false
        - oslo.messaging-tox-py35-func-amqp1:
            voting: false
        - oslo.messaging-tox-py35-func-rabbit:
            voting: false
        - oslo.messaging-tox-py35-func-zmq:
            voting: false

        - oslo.messaging-src-dsvm-full-rabbit-default
        - oslo.messaging-src-dsvm-full-amqp1-hybrid:
            voting: false
            branches: ^(?!stable/ocata).*$
        - oslo.messaging-src-dsvm-full-amqp1-dual-centos-7:
            voting: false
            branches: ^(?!stable/ocata).*$
        - oslo.messaging-src-dsvm-full-kafka-default-centos-7:
            voting: false
        - oslo.messaging-src-dsvm-full-kafka-default:
            voting: false
        - oslo.messaging-src-dsvm-full-pika-default:
            voting: false
        - oslo.messaging-src-dsvm-full-zmq-default:
            voting: false

        - oslo.messaging-src-grenade-dsvm:
            voting: false
        - oslo.messaging-src-grenade-dsvm-multinode:
            voting: false

        - oslo.messaging-telemetry-dsvm-integration-rabbit:
            voting: false
        - oslo.messaging-telemetry-dsvm-integration-amqp1:
            voting: false
        - oslo.messaging-telemetry-dsvm-integration-kafka:
            voting: false
        - oslo.messaging-telemetry-dsvm-integration-pika:
            voting: false
        - oslo.messaging-telemetry-dsvm-integration-zmq:
            voting: false

        - oslo.messaging-tempest-neutron-dsvm-src-rabbit-default
        - oslo.messaging-tempest-neutron-dsvm-src-amqp1-hybrid:
            voting: false
            branches: ^(?!stable/ocata).*$
        - oslo.messaging-tempest-neutron-dsvm-src-kafka-default:
            voting: false
        - oslo.messaging-tempest-neutron-dsvm-src-pika-default:
            voting: false
        - oslo.messaging-tempest-neutron-dsvm-src-zmq-default:
            voting: false

    gate:
      jobs:
        - oslo.messaging-tox-py27-func-rabbit
        - oslo.messaging-tox-py27-func-pika
        - oslo.messaging-src-dsvm-full-rabbit-default
        - oslo.messaging-tempest-neutron-dsvm-src-rabbit-default




    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - lib-forward-testing
      - release-notes-jobs-python3
      - periodic-stable-jobs
    post:
      jobs:
        - openstack-tox-cover
