
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-01T18:48:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e3020ca8b666f5089d7ee31df7f1490b16fec21e",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
