# Config file for automatic testing at travis-ci.org

dist: xenial
language: python
python:
    - "3.6"
    - "3.7"

install:
    - pip install -r requirements.txt coverage python-coveralls
    - python setup.py --quiet install

script:
    - python setup.py test

after_success:
    - coverage run --source codemetrics setup.py test
    - coveralls
