
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-26T07:34:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "27e9788ecfa0315272341bc7269a7e40136bd4bc",
 "version": "0.6.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
