---
- hosts: all
  tasks:
    - name: Disable Fedora's update repositories
      command: "dnf config-manager --set-disabled {{ item }}"
      with_items:
        - updates
        - updates-modular
      become: true
      when: ansible_distribution == 'Fedora'
    - name: Install libselinux-python
      package:
        name: libselinux-python
        state: present
      become: true
      when: ansible_distribution == 'Fedora'
    - name: Disable Debian's backports repositories
      lineinfile:
        path: /etc/apt/sources.list
        state: absent
        regexp: '.*backports.*'
      become: true
      when: ansible_distribution == 'Debian'
    - name: Adjust the shell of the user
      user:
        name: "{{ansible_user_id}}"
        shell: /bin/bash
      become: true
    - name: Add ~/.local/bin in the $PATH
      lineinfile:
        path: ~/.bashrc
        regexp: '# .local/bin path'
        line: 'export PATH=$PATH:~/.local/bin/  # .local/bin path'
    - import_role:
        name: virt_lightning
      vars:
        virt_lightning_run_tests: true
