# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Wed Sep 11 13:42:13 2019
#

import wx
from wx.lib.agw.floatspin import FloatSpin, EVT_FLOATSPIN, FS_LEFT, FS_RIGHT, FS_CENTRE, FS_READONLY

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class PanelTabTransform(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PanelTabTransform.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.window_splitter = wx.SplitterWindow(self, wx.ID_ANY, style=wx.SP_3D | wx.SP_BORDER)
        self.PanelLeftSide = wx.Panel(self.window_splitter, wx.ID_ANY)
        self.PanelTransformKernel = wx.Panel(self.PanelLeftSide, wx.ID_ANY)
        self.LabelPlaceholder2 = wx.StaticText(self.PanelTransformKernel, wx.ID_ANY, "LabelPlaceholder2")
        self.LabelPlaceholder3 = wx.StaticText(self.PanelTransformKernel, wx.ID_ANY, "LabelPlaceholder3")
        self.ButtonRun = wx.Button(self.PanelLeftSide, wx.ID_ANY, "Run")
        self.CheckProfile = wx.CheckBox(self.PanelLeftSide, wx.ID_ANY, "Freq Profile  ")
        self.CheckAbsolute = wx.CheckBox(self.PanelLeftSide, wx.ID_ANY, "Abs Freq Profile  ")
        self.CheckProfileExtended = wx.CheckBox(self.PanelLeftSide, wx.ID_ANY, "Ext Profile")
        self.CheckAbsoluteExtended = wx.CheckBox(self.PanelLeftSide, wx.ID_ANY, "Ext-Absolute Profile  ")
        self.CheckGradient = wx.CheckBox(self.PanelLeftSide, wx.ID_ANY, "Gradient Plot  ")
        self.CheckWaveform = wx.CheckBox(self.PanelLeftSide, wx.ID_ANY, "Waveform [re/im]")
        self.CheckWaveformMagn = wx.CheckBox(self.PanelLeftSide, wx.ID_ANY, "Waveform [Magn]")
        self.CheckWaveformPhase = wx.CheckBox(self.PanelLeftSide, wx.ID_ANY, "Waveform [deg]")
        self.ComboUsageType = wx.ComboBox(self.PanelLeftSide, wx.ID_ANY, choices=["Excite", "Inversion", "Spin-Echo Echo Echo", "Saturation"], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)
        self.PanelGradRefocus = wx.Panel(self.PanelLeftSide, wx.ID_ANY)
        self.CheckGradRefocus = wx.CheckBox(self.PanelGradRefocus, wx.ID_ANY, "Grad Refoc Profile    Grad Value:")
        self.FloatGradRefocus = FloatSpin(self.PanelGradRefocus, wx.ID_ANY, value=0.5, digits=5, min_val=0.0, max_val=100.0, increment=1.0, agwStyle=FS_LEFT, style=0)
        self.window_1_pane_results = wx.ScrolledWindow(self.window_splitter, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.PanelRhs = wx.Panel(self.window_1_pane_results, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_run, self.ButtonRun)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckProfile)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckAbsolute)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckProfileExtended)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckAbsoluteExtended)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckGradient)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckWaveform)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckWaveformMagn)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckWaveformPhase)
        self.Bind(wx.EVT_COMBOBOX, self.on_usage, self.ComboUsageType)
        self.Bind(wx.EVT_CHECKBOX, self.on_check_grad_refocus, self.CheckGradRefocus)
        self.Bind( EVT_FLOATSPIN, self.on_float_grad_refocus, self.FloatGradRefocus)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PanelTabTransform.__set_properties
        self.ComboUsageType.SetSelection(1)
        self.PanelGradRefocus.Hide()
        self.window_1_pane_results.SetScrollRate(10, 10)
        self.window_splitter.SetMinimumPaneSize(20)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PanelTabTransform.__do_layout
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.StaticBoxSizer(wx.StaticBox(self.PanelLeftSide, wx.ID_ANY, "Pulse Plot Controls"), wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2 = wx.FlexGridSizer(5, 2, 0, 0)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        SizerTransformKernel = wx.BoxSizer(wx.VERTICAL)
        GridUserParameters = wx.FlexGridSizer(1, 3, 4, 4)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.LabelPlaceholder2, 0, wx.EXPAND, 0)
        SizerTransformKernel.Add(sizer_3, 0, wx.EXPAND, 0)
        GridUserParameters.Add(self.LabelPlaceholder3, 0, 0, 0)
        GridUserParameters.AddGrowableCol(1)
        SizerTransformKernel.Add(GridUserParameters, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.EXPAND, 4)
        self.PanelTransformKernel.SetSizer(SizerTransformKernel)
        sizer_5.Add(self.PanelTransformKernel, 1, wx.ALL | wx.EXPAND, 4)
        sizer_8.Add(self.ButtonRun, 0, wx.ALIGN_CENTER, 0)
        sizer_5.Add(sizer_8, 0, wx.ALIGN_CENTER | wx.TOP, 4)
        grid_sizer_2.Add(self.CheckProfile, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        grid_sizer_2.Add(self.CheckAbsolute, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        grid_sizer_2.Add(self.CheckProfileExtended, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        grid_sizer_2.Add(self.CheckAbsoluteExtended, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        grid_sizer_2.Add(self.CheckGradient, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        grid_sizer_2.Add(self.CheckWaveform, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        grid_sizer_2.Add(self.CheckWaveformMagn, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        grid_sizer_2.Add(self.CheckWaveformPhase, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        label_2 = wx.StaticText(self.PanelLeftSide, wx.ID_ANY, "Usage Type: ", style=wx.ALIGN_RIGHT)
        grid_sizer_2.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)
        grid_sizer_2.Add(self.ComboUsageType, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)
        sizer_9.Add(grid_sizer_2, 0, wx.EXPAND, 0)
        sizer_6.Add(self.CheckGradRefocus, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)
        sizer_6.Add(self.FloatGradRefocus, 0, wx.EXPAND, 0)
        self.PanelGradRefocus.SetSizer(sizer_6)
        sizer_9.Add(self.PanelGradRefocus, 0, wx.EXPAND, 0)
        sizer_5.Add(sizer_9, 0, wx.ALL | wx.EXPAND, 6)
        self.PanelLeftSide.SetSizer(sizer_5)
        sizer_1.Add(self.PanelRhs, 1, wx.EXPAND, 0)
        self.window_1_pane_results.SetSizer(sizer_1)
        self.window_splitter.SplitVertically(self.PanelLeftSide, self.window_1_pane_results)
        sizer_7.Add(self.window_splitter, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_7)
        sizer_7.Fit(self)
        self.Layout()
        # end wxGlade

    def on_run(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_run' not implemented!")
        event.Skip()

    def on_check(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_check' not implemented!")
        event.Skip()

    def on_usage(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_usage' not implemented!")
        event.Skip()

    def on_check_grad_refocus(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_check_grad_refocus' not implemented!")
        event.Skip()

    def on_float_grad_refocus(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_float_grad_refocus' not implemented!")
        event.Skip()

# end of class PanelTabTransform

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.PanelTabTransform = PanelTabTransform(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(self.PanelTabTransform, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_4)
        sizer_4.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame
