# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Wed Sep 11 13:34:53 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class PanelGaussian(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PanelGaussian.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.TextTipAngle = wx.TextCtrl(self, wx.ID_ANY, "")
        self.TextTimeSteps = wx.TextCtrl(self, wx.ID_ANY, "")
        self.TextDuration = wx.TextCtrl(self, wx.ID_ANY, "")
        self.TextBandwidth = wx.TextCtrl(self, wx.ID_ANY, "")
        self.ComboBoxFilterType = wx.ComboBox(self, wx.ID_ANY, choices=["None-selected", "Cosine", "Hamming"], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)
        self.TextFilterApplication = wx.TextCtrl(self, wx.ID_ANY, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT_ENTER, self.on_tip_angle, self.TextTipAngle)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_duration, self.TextDuration)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PanelGaussian.__set_properties
        self.TextTipAngle.SetMinSize((175, -1))
        self.TextTimeSteps.SetMinSize((175, -1))
        self.TextDuration.SetMinSize((175, -1))
        self.TextBandwidth.SetMinSize((175, -1))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PanelGaussian.__do_layout
        sizer_create_gaussian_params = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Pulse Params"), wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Filter Application (%)"), wx.HORIZONTAL)
        sizer_8 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Filter Type"), wx.HORIZONTAL)
        grid_sizer_gaussian_params = wx.FlexGridSizer(6, 3, 3, 5)
        label_2_copy = wx.StaticText(self, wx.ID_ANY, "Tip Angle: ", style=wx.ALIGN_RIGHT)
        grid_sizer_gaussian_params.Add(label_2_copy, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_gaussian_params.Add(self.TextTipAngle, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_3 = wx.StaticText(self, wx.ID_ANY, "degrees")
        grid_sizer_gaussian_params.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_2_copy_1 = wx.StaticText(self, wx.ID_ANY, "Time Steps: ", style=wx.ALIGN_RIGHT)
        grid_sizer_gaussian_params.Add(label_2_copy_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_gaussian_params.Add(self.TextTimeSteps, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_4 = wx.StaticText(self, wx.ID_ANY, "increments")
        grid_sizer_gaussian_params.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_2_copy_2 = wx.StaticText(self, wx.ID_ANY, "Duration: ", style=wx.ALIGN_RIGHT)
        grid_sizer_gaussian_params.Add(label_2_copy_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_gaussian_params.Add(self.TextDuration, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_5 = wx.StaticText(self, wx.ID_ANY, "milliseconds")
        grid_sizer_gaussian_params.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_2_copy_3 = wx.StaticText(self, wx.ID_ANY, "Bandwidth: ", style=wx.ALIGN_RIGHT)
        grid_sizer_gaussian_params.Add(label_2_copy_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_gaussian_params.Add(self.TextBandwidth, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_5_copy = wx.StaticText(self, wx.ID_ANY, "kilohertz")
        grid_sizer_gaussian_params.Add(label_5_copy, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_gaussian_params.Add((0, 0), 0, 0, 0)
        grid_sizer_gaussian_params.Add((0, 0), 0, 0, 0)
        grid_sizer_gaussian_params.Add((0, 0), 0, 0, 0)
        grid_sizer_gaussian_params.Add((75, 2), 0, 0, 0)
        grid_sizer_gaussian_params.Add((154, 2), 0, 0, 0)
        grid_sizer_gaussian_params.Add((20, 2), 0, 0, 0)
        sizer_create_gaussian_params.Add(grid_sizer_gaussian_params, 0, wx.EXPAND, 0)
        sizer_8.Add(self.ComboBoxFilterType, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
        sizer_7.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_9.Add(self.TextFilterApplication, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
        sizer_7.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_create_gaussian_params.Add(sizer_7, 0, wx.EXPAND, 0)
        sizer_create_gaussian_params.Add((0, 0), 0, 0, 0)
        self.SetSizer(sizer_create_gaussian_params)
        sizer_create_gaussian_params.Fit(self)
        self.Layout()
        # end wxGlade

    def on_tip_angle(self, event):  # wxGlade: PanelGaussian.<event_handler>
        print("Event handler 'on_tip_angle' not implemented!")
        event.Skip()

    def on_duration(self, event):  # wxGlade: PanelGaussian.<event_handler>
        print("Event handler 'on_duration' not implemented!")
        event.Skip()

# end of class PanelGaussian

class TestCreateGaussianFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: TestCreateGaussianFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.PanelGaussian = PanelGaussian(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: TestCreateGaussianFrame.__set_properties
        self.SetTitle("frame_create_pulse")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: TestCreateGaussianFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.PanelGaussian, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class TestCreateGaussianFrame
