# Generated by Django 2.0.7 on 2019-05-14 18:48

from django.db import migrations


def forwards(apps, schema_editor):

    for i, attr in enumerate(apps.get_model('attributes', 'ProductAttr').objects.all(), start=1):
        attr.order = i
        attr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_attr_ordering'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
