
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-07T12:06:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2ec1d9b553ed5990804ad42b7e17141f8596276",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
