[tool.poetry]
name = "markdown_formatter"
version = "0.0.4"
description = ""
authors = ["Trim21 <i@trim21.me>"]
readme='readme.md'
keywords=['markdown','formatter']
homepage='https://github.com/Trim21/markdown_formatter'
repository='https://github.com/Trim21/markdown_formatter'
packages=[
    {include='markdown_formatter'},
]

[tool.poetry.dependencies]
python = "^3.6"
cython = "^0.29.13"
mistune = "^0.8.4"
click = "^7.0"
black = {version = ">=18.3,<20.0", allows-prereleases = true}
dataclasses = {version = "^0.6.0", python = "<3.7"}
chardet = "^3.0"
[tool.poetry.dev-dependencies]

yapf = "^0.28.0"

# tests
pytest = "5.2.1"
pytest-mock = "1.11.1"
pytest-asyncio = "0.10.0"
pytest-faker = "2.0.0"
asynctest = "0.13.0"
pytest-jest = "0.3.0"
pytest-rerunfailures = "7.0"
mock = "3.0.5"
# linter and formatter
pre-commit = "1.18.3"
autoflake = "1.3.1"
isort = "4.3.21"
pyupgrade = "1.24.1"
flake8-comprehensions = "2.2.0"
flake8-bugbear = "19.8.0"
flake8-commas = "2.0.0"
flake8-mutable = "1.2.0"
livereload = "2.6.1"
doc8 = "0.8.0"
coverage = "4.5.4"
# build docs
sphinx = "2.2"
sphinxcontrib-httpdomain = "1.7"
sphinxcontrib-httpexample = "0.10.3"
sphinxcontrib-openapi = {version = "0.5.0", extras = ["markdown"]}
sphinx-issues = "1.2"
sphinx-rtd-theme = "0.4.3"
m2r = "0.2.1"

[tool.poetry.scripts]
markdown_formatter = "markdown_formatter.cli:run_main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
