
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-03T02:12:40-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b049d72f6a5f71855c762112959642ac402693a9",
 "version": "0+untagged.559.gb049d72"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
