[tool.poetry]
name = "doka"
version = "0.4.8"
description = ""
authors = ["axxil <axxil@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.6"
fire = "^0.1.3"
python-dotenv = "^0.10.3"
marshmallow = "^2.19"
pyyaml = "^5.1"
requests = "^2.22"
termcolor = "^1.1"

[tool.poetry.scripts]
doka = "doka:main"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
