# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streamlit/proto/Multiselectbox.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='streamlit/proto/Multiselectbox.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$streamlit/proto/Multiselectbox.proto\"M\n\x0eMultiselectbox\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\x03 \x03(\x05\x12\x0f\n\x07options\x18\x04 \x03(\tb\x06proto3')
)




_MULTISELECTBOX = _descriptor.Descriptor(
  name='Multiselectbox',
  full_name='Multiselectbox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Multiselectbox.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='Multiselectbox.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='default', full_name='Multiselectbox.default', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='Multiselectbox.options', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['Multiselectbox'] = _MULTISELECTBOX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Multiselectbox = _reflection.GeneratedProtocolMessageType('Multiselectbox', (_message.Message,), dict(
  DESCRIPTOR = _MULTISELECTBOX,
  __module__ = 'streamlit.proto.Multiselectbox_pb2'
  # @@protoc_insertion_point(class_scope:Multiselectbox)
  ))
_sym_db.RegisterMessage(Multiselectbox)


# @@protoc_insertion_point(module_scope)
