
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-10T10:54:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e535f1b0c964d8a9b80a2c09f93c0c3bc3ef9fad",
 "version": "0.1.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
