
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-07T14:18:32+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "711d11d24acdf98f4bdf0c4a3e75c993d5778b57",
 "version": "1.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
