#!/usr/bin/env python3

def get_parsed_args():
    parser = argparse.ArgumentParser(
        description='Prepare a series of images.',
        )
    parser.add_argument(
        'target_name', type=str,
        help='Name of the target')
    parser.add_argument(
        '--calib-points', type=str,
        help=('2-columns text file containing indices and wavelength of '
              'at least two wavelength calibration points. '
              'If not specified, --grating-period must be passed.'
            ))
    parser.add_argument(
        '--master-calib-rotated', type=str,
        help=('Rotated wavelength calibration image generated by rotate_spectra'
              ' Default: {target_name}/master_calib_rotated.fits'))
    parser.add_argument(
        '--output-path', type=str,
        help='Directory where output files are saved. Default: {name}/')
    parser.add_argument(
        '-O', '--overwrite', action='store_true',
        help='Overwrite outputs if they already exist.')
    args = parser.parse_args()

    return args

def main():
    raise NotImplementedError

if __name__ == '__main__':
    main()
