[tool.poetry]
name = "task-recurrence"
version = "3.0.1"
description = "A Recurrence library for todo applications that provide next date calculation and string generation"
authors = ["BeatLink <beatlink@protonmail.com>"]
license = "GPL-3.0+"

packages = [{include = "task_recurrence"}]

[tool.poetry.dependencies]
python = "^3.6"
arrow = "^0.14.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
