# coding: utf-8

"""
    OOXML Automation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0-no-tags
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SharedFillMap(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'fill_type_id': 'int',
        'solid_fill': 'SharedSolidFills',
        'gradient_fill': 'SharedGradientFills',
        'image_fill': 'SharedImageFills',
        'id': 'str',
        'date_created': 'datetime',
        'user_created': 'str',
        'date_modified': 'datetime',
        'user_modified': 'str'
    }

    attribute_map = {
        'fill_type_id': 'fillTypeId',
        'solid_fill': 'solidFill',
        'gradient_fill': 'gradientFill',
        'image_fill': 'imageFill',
        'id': 'id',
        'date_created': 'dateCreated',
        'user_created': 'userCreated',
        'date_modified': 'dateModified',
        'user_modified': 'userModified'
    }

    def __init__(self, fill_type_id=None, solid_fill=None, gradient_fill=None, image_fill=None, id=None, date_created=None, user_created=None, date_modified=None, user_modified=None):  # noqa: E501
        """SharedFillMap - a model defined in OpenAPI"""  # noqa: E501

        self._fill_type_id = None
        self._solid_fill = None
        self._gradient_fill = None
        self._image_fill = None
        self._id = None
        self._date_created = None
        self._user_created = None
        self._date_modified = None
        self._user_modified = None
        self.discriminator = None

        if fill_type_id is not None:
            self.fill_type_id = fill_type_id
        if solid_fill is not None:
            self.solid_fill = solid_fill
        if gradient_fill is not None:
            self.gradient_fill = gradient_fill
        if image_fill is not None:
            self.image_fill = image_fill
        if id is not None:
            self.id = id
        if date_created is not None:
            self.date_created = date_created
        if user_created is not None:
            self.user_created = user_created
        if date_modified is not None:
            self.date_modified = date_modified
        if user_modified is not None:
            self.user_modified = user_modified

    @property
    def fill_type_id(self):
        """Gets the fill_type_id of this SharedFillMap.  # noqa: E501


        :return: The fill_type_id of this SharedFillMap.  # noqa: E501
        :rtype: int
        """
        return self._fill_type_id

    @fill_type_id.setter
    def fill_type_id(self, fill_type_id):
        """Sets the fill_type_id of this SharedFillMap.


        :param fill_type_id: The fill_type_id of this SharedFillMap.  # noqa: E501
        :type: int
        """

        self._fill_type_id = fill_type_id

    @property
    def solid_fill(self):
        """Gets the solid_fill of this SharedFillMap.  # noqa: E501


        :return: The solid_fill of this SharedFillMap.  # noqa: E501
        :rtype: SharedSolidFills
        """
        return self._solid_fill

    @solid_fill.setter
    def solid_fill(self, solid_fill):
        """Sets the solid_fill of this SharedFillMap.


        :param solid_fill: The solid_fill of this SharedFillMap.  # noqa: E501
        :type: SharedSolidFills
        """

        self._solid_fill = solid_fill

    @property
    def gradient_fill(self):
        """Gets the gradient_fill of this SharedFillMap.  # noqa: E501


        :return: The gradient_fill of this SharedFillMap.  # noqa: E501
        :rtype: SharedGradientFills
        """
        return self._gradient_fill

    @gradient_fill.setter
    def gradient_fill(self, gradient_fill):
        """Sets the gradient_fill of this SharedFillMap.


        :param gradient_fill: The gradient_fill of this SharedFillMap.  # noqa: E501
        :type: SharedGradientFills
        """

        self._gradient_fill = gradient_fill

    @property
    def image_fill(self):
        """Gets the image_fill of this SharedFillMap.  # noqa: E501


        :return: The image_fill of this SharedFillMap.  # noqa: E501
        :rtype: SharedImageFills
        """
        return self._image_fill

    @image_fill.setter
    def image_fill(self, image_fill):
        """Sets the image_fill of this SharedFillMap.


        :param image_fill: The image_fill of this SharedFillMap.  # noqa: E501
        :type: SharedImageFills
        """

        self._image_fill = image_fill

    @property
    def id(self):
        """Gets the id of this SharedFillMap.  # noqa: E501


        :return: The id of this SharedFillMap.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SharedFillMap.


        :param id: The id of this SharedFillMap.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def date_created(self):
        """Gets the date_created of this SharedFillMap.  # noqa: E501


        :return: The date_created of this SharedFillMap.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this SharedFillMap.


        :param date_created: The date_created of this SharedFillMap.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def user_created(self):
        """Gets the user_created of this SharedFillMap.  # noqa: E501


        :return: The user_created of this SharedFillMap.  # noqa: E501
        :rtype: str
        """
        return self._user_created

    @user_created.setter
    def user_created(self, user_created):
        """Sets the user_created of this SharedFillMap.


        :param user_created: The user_created of this SharedFillMap.  # noqa: E501
        :type: str
        """

        self._user_created = user_created

    @property
    def date_modified(self):
        """Gets the date_modified of this SharedFillMap.  # noqa: E501


        :return: The date_modified of this SharedFillMap.  # noqa: E501
        :rtype: datetime
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this SharedFillMap.


        :param date_modified: The date_modified of this SharedFillMap.  # noqa: E501
        :type: datetime
        """

        self._date_modified = date_modified

    @property
    def user_modified(self):
        """Gets the user_modified of this SharedFillMap.  # noqa: E501


        :return: The user_modified of this SharedFillMap.  # noqa: E501
        :rtype: str
        """
        return self._user_modified

    @user_modified.setter
    def user_modified(self, user_modified):
        """Sets the user_modified of this SharedFillMap.


        :param user_modified: The user_modified of this SharedFillMap.  # noqa: E501
        :type: str
        """

        self._user_modified = user_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SharedFillMap):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
