[tool.poetry]

name = "verchew"
version = "1.6.3"  # also update verchew/script.py
description = "System dependency version checker."

license = "MIT"

authors = ["Jace Browning <jacebrowning@gmail.com>"]

readme = "README.md"

homepage = "https://pypi.org/project/verchew"
documentation = "https://verchew.readthedocs.io"
repository = "https://github.com/jacebrowning/verchew"

keywords = [
    "dependencies",
    "configuration management",
    "continuous integration",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.4",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Testing",
    "Topic :: System :: Installation/Setup",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]

python = "^2.7.9 || ^3.4"

[tool.poetry.dev-dependencies]

# Formatters
# TODO: Enable black after dropping legacy Python support
#black = "=18.9b0"
isort = "=4.3.4"

# Linters
# TODO: Enable mypy after dropping legacy Python support
# mypy = "*"
pydocstyle = "^3"
pylint = "*"

# Testing
pytest = "=4.2.0"
pytest-cov = "*"
pytest-describe = "*"
pytest-expecter = "*"
pytest-random = "*"
scripttest = "*"
attrs = "=19.1.0"  # avoid bug in 19.2.0, pulled in by test

# Reports
coveragespace = "*"

# Documentation
mkdocs = "^1.0.4"
backports-abc = { version = "*", python = "^2.7" }  # needed for 'mkdocs'
pygments = "*"

# Tooling
pyinstaller = "*"
sniffer = "*"
MacFSEvents = { version = "*", platform = "darwin" }
pync = { version = "*", platform = "darwin" }

[tool.poetry.scripts]

verchew = "verchew.script:main"

[tool.black]

py36 = false
skip-string-normalization = true

[build-system]

requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
