
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-25T14:19:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "52ce5496744485b11194111c1b93cff8ee38959b",
 "version": "0.22.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
