
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-10T11:29:16-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "52b5ff8b2052c8525091165bf067774639255bbd",
 "version": "0+untagged.578.g52b5ff8.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
