
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-06T11:14:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "eee6abd8493567c7eb2b8b476737ba5f7bbebdda",
 "version": "0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
