
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-05T17:38:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b62b76111e260f59e8a522feb65d727432592be",
 "version": "v0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
