
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ea333e3f7f973f7e1842047561ab846b301e960b",
 "version": "7.5.2.beta3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
