# Generated by Django 2.1.2 on 2018-10-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheet_id',
            field=models.SlugField(help_text='Sheet ID from URL', verbose_name='Google Sheet ID'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='title',
            field=models.CharField(help_text='A title for this sheet', max_length=250, verbose_name='Project title'),
        ),
    ]
