# Generated by Django 2.2.6 on 2019-10-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0010_auto_20191002_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiedoc',
            name='version',
            field=models.CharField(choices=[('v1', 'v1'), ('v2', 'v2')], default='v2', help_text='Should be the latest version when created.', max_length=2),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='version',
            field=models.CharField(choices=[('v1', 'v1'), ('v2', 'v2')], default='v2', help_text='Should be the latest version when created.', max_length=2),
        ),
    ]
