
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-30T18:25:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9bf748bc1832c32b55f01a2a8ee5784feeba41ca",
 "version": "0.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
