# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toktokkie/gui/qt_designer/book_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BookWidget(object):
    def setupUi(self, BookWidget):
        BookWidget.setObjectName("BookWidget")
        BookWidget.resize(661, 369)
        self.gridLayout = QtWidgets.QGridLayout(BookWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.name = QtWidgets.QLabel(BookWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.name.setFont(font)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.open_directory_button = QtWidgets.QPushButton(BookWidget)
        self.open_directory_button.setObjectName("open_directory_button")
        self.gridLayout.addWidget(self.open_directory_button, 5, 0, 1, 1)
        self.icon_label = QtWidgets.QLabel(BookWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_label.sizePolicy().hasHeightForWidth())
        self.icon_label.setSizePolicy(sizePolicy)
        self.icon_label.setMinimumSize(QtCore.QSize(256, 256))
        self.icon_label.setMaximumSize(QtCore.QSize(256, 256))
        self.icon_label.setText("")
        self.icon_label.setPixmap(QtGui.QPixmap("../../../../../Downloads/pokemon_folder_icon_by_mikromike-d8mldi8.png"))
        self.icon_label.setScaledContents(True)
        self.icon_label.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_label.setObjectName("icon_label")
        self.gridLayout.addWidget(self.icon_label, 3, 0, 1, 1)
        self.frame = QtWidgets.QFrame(BookWidget)
        self.frame.setEnabled(True)
        self.frame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2.addWidget(self.frame_2, 4, 0, 1, 4)
        self.tags_edit = QtWidgets.QLineEdit(self.frame)
        self.tags_edit.setText("")
        self.tags_edit.setObjectName("tags_edit")
        self.gridLayout_2.addWidget(self.tags_edit, 1, 1, 1, 3)
        self.isbn_url_button = QtWidgets.QPushButton(self.frame)
        self.isbn_url_button.setObjectName("isbn_url_button")
        self.gridLayout_2.addWidget(self.isbn_url_button, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.confirm_changes_button = QtWidgets.QPushButton(self.frame)
        self.confirm_changes_button.setObjectName("confirm_changes_button")
        self.gridLayout_2.addWidget(self.confirm_changes_button, 5, 1, 1, 1)
        self.isbn_edit = QtWidgets.QLineEdit(self.frame)
        self.isbn_edit.setText("")
        self.isbn_edit.setObjectName("isbn_edit")
        self.gridLayout_2.addWidget(self.isbn_edit, 2, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.media_type_label = QtWidgets.QLabel(self.frame)
        self.media_type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.media_type_label.setObjectName("media_type_label")
        self.gridLayout_2.addWidget(self.media_type_label, 0, 1, 1, 3)
        self.gridLayout.addWidget(self.frame, 0, 1, 7, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 0, 1, 1)

        self.retranslateUi(BookWidget)
        QtCore.QMetaObject.connectSlotsByName(BookWidget)
        BookWidget.setTabOrder(self.tags_edit, self.isbn_edit)
        BookWidget.setTabOrder(self.isbn_edit, self.isbn_url_button)
        BookWidget.setTabOrder(self.isbn_url_button, self.confirm_changes_button)

    def retranslateUi(self, BookWidget):
        _translate = QtCore.QCoreApplication.translate
        BookWidget.setWindowTitle(_translate("BookWidget", "Form"))
        self.name.setText(_translate("BookWidget", "Name"))
        self.open_directory_button.setText(_translate("BookWidget", "Open Directory"))
        self.isbn_url_button.setText(_translate("BookWidget", "Go"))
        self.confirm_changes_button.setText(_translate("BookWidget", "Confirm Changes"))
        self.label_2.setText(_translate("BookWidget", "ISBN"))
        self.label_4.setText(_translate("BookWidget", "Media Type"))
        self.label_3.setText(_translate("BookWidget", "Tags"))
        self.media_type_label.setText(_translate("BookWidget", "Media Type"))
