[tool.poetry]
name = "scylla_client"
version = "0.2.1"
description = "Scylla - client for charybdis permission manager"
authors = ["Alexander Lavrov <egnod@ya.ru>"]
license = "MIT"
packages = [

    {include = "scylla"}

]

[tool.poetry.dependencies]
python = "^3.7"
sitri = "^0.4.0"
requests = "^2.22"

[tool.poetry.dev-dependencies]
pytest-httpserver = "^0.3.4"
pre-commit = "^1.18"
bumpversion = "^0.5.3"
pytest = "^5.2"
turmalin = "^2.5"
mypy = "^0.730.0"
pytest-cov = "^2.8"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
  )
)
'''
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
