sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  matrix:
    - DJANGO_VERSION="Django>=1.11,<2.0"
    - DJANGO_VERSION="Django>=2.0,<2.1"
    - DJANGO_VERSION="Django>=2.1,<2.2"
    - DJANGO_VERSION="Django>=2.2,<3.0"
    - DJANGO_VERSION="--pre Django>=3.0,<3.1"
    - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install 'coverage<4' # coverage>=4 has issues with python3
  - pip install -q $DJANGO_VERSION
  - pip install -q coveralls
  - pip install django-admin-tools
  - pip install -r requirements.txt

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION="Django>=2.0,<2.1"
    - python: "2.7"
      env: DJANGO_VERSION="Django>=2.1,<2.2"
    - python: "2.7"
      env: DJANGO_VERSION="Django>=2.2,<3.0"
    - python: "2.7"
      env: DJANGO_VERSION="--pre Django>=3.0,<3.1"
    - python: "2.7"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.4"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.4"
      env: DJANGO_VERSION="--pre Django>=3.0,<3.1"
    - python: "3.4"
      env: DJANGO_VERSION="Django>=2.1,<2.2"
    - python: "3.4"
      env: DJANGO_VERSION="Django>=2.2,<3.0"
    - python: "3.5"
      env: DJANGO_VERSION="--pre Django>=3.0,<3.1"
    - python: "3.5"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
  allow_failures:
    - env: DJANGO_VERSION="--pre Django>=3.0,<3.1"
    - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

script:
    - django-admin --version
    - python -Wall $VIRTUAL_ENV/bin/coverage run setup.py test

after_success:
    - coveralls
