# coding: utf-8

# flake8: noqa

"""
    Spotii Notification API

    API for notification things  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from notification_client.notification.default_api import DefaultApi
# import ApiClient
from notification_client.api_client import ApiClient
from notification_client.configuration import Configuration
# import models into sdk package
from notification_client.notification.body import Body
from notification_client.notification.body1 import Body1
