language: python

sudo: false

matrix:
    include:
        - python: '2.5'
          dist: trusty
          sudo: false
          env:

        - python: '2.6'
          dist: trusty
          sudo: false
          env:

        - python: '2.7'
          dist: trusty
          sudo: false
          env:

        - python: '3.1'
          dist: trusty
          sudo: false
          env:

        - python: '3.2'
          dist: trusty
          sudo: false
          env:

        - python: '3.3'
          dist: trusty
          sudo: false
          env:

        - python: '3.4'
          dist: trusty
          sudo: false
          env:

        - python: '3.5'
          dist: trusty
          sudo: false
          env:

        - python: '3.6'
          dist: trusty
          sudo: false
          env:
            - COVERAGE="true"
            - DILL="true"

        - python: '3.7'
          dist: xenial
          sudo: true
          env:

        - python: '3.8-dev'
          dist: xenial
          sudo: true
          env:
            - PYVERSION="3.8"

        - python: 'nightly'
          dist: xenial
          sudo: true
          env:
            - PYVERSION="3.8"

        - python: 'pypy'
          dist: trusty
          sudo: false
          env:

        - python: 'pypy3'
          dist: trusty
          sudo: false
          env:

    allow_failures:
        - python: '2.5'
        - python: '2.6'
        - python: '3.1'
        - python: '3.2'
        - python: '3.3'
        - python: '3.8-dev'
        - python: 'nightly'
        - python: 'pypy'
        - python: 'pypy3'
    fast_finish: true

cache:
    pip: true

before_install:
    - set -e  # fail on any error
    - if [[ $COVERAGE == "true" ]]; then pip install coverage; fi
    - if [[ $DILL == "true" ]]; then pip install dill; fi

install:
    - python setup.py build && python setup.py install

script:
    - if [[ $PYVERSION != "3.8" ]]; then PYVERSION=$TRAVIS_PYTHON_VERSION ; fi
    - cd py$PYVERSION
    - cp ../.coveragerc .coveragerc
    - for test in multiprocess/tests/__init__.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done
    - for test in multiprocess/tests/*.py; do if [[ $test != "__"* ]]; then echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; fi; done
    - if [[ $COVERAGE == "true" ]]; then cat .coverage; else echo ''; fi
    - if [[ $COVERAGE == "true" ]]; then mv .coverage ../.coverage; else echo ''; fi
    - cd ..

after_success:
    - if [[ $COVERAGE == "true" ]]; then bash <(curl -s https://codecov.io/bash); else echo ''; fi
