sudo: required
language: python
services: docker
env:
    - DISTRO=fedora-29
    - DISTRO=fedora-latest
    - DISTRO=fedora-rawhide
install: true
before_script:
    - |
        if [ "${TRAVIS_EVENT_TYPE}" = "cron" ]; then
            PYTEST_ADDOPTS="-m 1"
        else
            PYTEST_ADDOPTS="-m 'not long_running'"
        fi
script:
    - make PYTEST_ADDOPTS="${PYTEST_ADDOPTS}" test-docker
