[tool.poetry]
name = "kafkahelpers"
version = "0.3.2"
description = ""
authors = ["Jesse Jaggars <jhjaggars@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
attrs = "^18.2"
kafka-python = "^1.4"
aiokafka = "^0.5.0"

[tool.poetry.dev-dependencies]
pytest = "^4.0"
pytest-asyncio = "^0.9.0"
pytest-cov = "^2.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
