# Data about your tablet
# You can get this information by observing the raw output from the USB
xinput_name: kamvas-pen
vendor_id: 0x256c
product_id: 0x006e
pen:
    max_x: 58752
    max_y: 33048
    max_pressure: 8191
    max_tilt_x: 60
    max_tilt_y: 60
    resolution: 5080

# User preferences
default_display: HDMI1
default_action: program1
actions:
    program1:
        pen_touch: BTN_TOUCH
        pen_button_1: KEY_LEFTCTRL
        pen_button_1_touch: KEY_LEFTCTRL+BTN_TOUCH
        pen_button_2: ''
        pen_button_2_touch: BTN_STYLUS
        tablet_buttons:
            - KEY_E
            - ''
            - KEY_LEFTCTRL+KEY_LEFTSHIFT+KEY_Z
            - KEY_LEFTCTRL+KEY_Z
            - ''
        tablet_scrollbar_increase: KEY_LEFTCTRL+KEY_KPMINUS
        tablet_scrollbar_decrease: KEY_LEFTCTRL+KEY_KPPLUS
        tablet_scrollbar:
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
    program2:
        pen_touch: BTN_TOUCH
        pen_button_1: KEY_LEFTCTRL
        pen_button_1_touch: KEY_LEFTCTRL+BTN_TOUCH
        pen_button_2: ''
        pen_button_2_touch: BTN_STYLUS
        tablet_buttons:
            - KEY_E
            - ''
            - KEY_LEFTCTRL+KEY_LEFTSHIFT+KEY_Z
            - KEY_LEFTCTRL+KEY_Z
            - ''
        tablet_scrollbar_increase: KEY_LEFTCTRL+KEY_KPMINUS
        tablet_scrollbar_decrease: KEY_LEFTCTRL+KEY_KPPLUS
        tablet_scrollbar:
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
