# Autogenerated by Astropy-affiliated package astrowidgets's setup.py on 2019-10-05 19:09:50 UTC
from __future__ import unicode_literals
import datetime

version = "0.1.0"
githash = "568ee3362b1c58104ee8fc602870c1b22c16a71e"


major = 0
minor = 1
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2019, 10, 5, 19, 9, 50)
debug = False

astropy_helpers_version = "3.1.dev1156"
