
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-12T19:23:22-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "f1680a2d597d196cac13ccababde22c2e4455f94",
 "version": "0+untagged.582.gf1680a2.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
