from zlparse.parse_time.common import *

exec_func = {
    'extime_fbsj': extime_fbsj,
    'extime_xxsj': extime_xxsj,
    'extime_transfrom_yunan': extime_transfrom_yunan,
    'strptime_transfrom_yue_r_n': strptime_transfrom_yue_r_n,
    'extime': extime,
    'extime_v2': extime_v2,
    'extime_fbsj_v2': extime_fbsj_v2,
    'extime_xxsj_v2': extime_xxsj_v2,
    'extime_guangdong_guangdongsheng_zfcg': extime_guangdong_guangdongsheng_zfcg,
    'extime_qg_1_zfcg': extime_qg_1_zfcg,
    'extime_daili_www_xhtc_com_cn': extime_daili_www_xhtc_com_cn,
    'extime_henan_henansheng_1_daili': extime_henan_henansheng_1_daili,
    'extime_ningxia_ningxiasheng_zfcg_ningxia_yinchuan_zfcg': extime_ningxia_ningxiasheng_zfcg_ningxia_yinchuan_zfcg,
    'extime_shandong_qingdao_zfcg': extime_shandong_qingdao_zfcg,
    'extime_qycg_eps_hnagroup_com': extime_qycg_eps_hnagroup_com,
    'extime_daili_www_cfet_com_cn': extime_daili_www_cfet_com_cn,
    'extime_sichuan_luzhou_ggzy':extime_sichuan_luzhou_ggzy,
    'extime_liaoning_huludao_ggzy':extime_liaoning_huludao_ggzy,
    'extime_jiangxi_dexing_ggzy1':extime_jiangxi_dexing_ggzy1,
    'extime_guangxi_baise_gcjs':extime_guangxi_baise_gcjs,
    'extime_tail':extime_tail,
    'extime_shanxi_hanzhong_gcjs':extime_shanxi_hanzhong_gcjs,
    'extime_shandong_shandongsheng_gcjs':extime_shandong_shandongsheng_gcjs,
    'extime_shandong_zoucheng_ggzy':extime_shandong_zoucheng_ggzy,
    'extime_daili_www_kanti_cn':extime_daili_www_kanti_cn,
    'extime_qycg_www_zmzb_com':extime_qycg_www_zmzb_com,
    'extime_jiangxi_yingtan_ggzy':extime_jiangxi_yingtan_ggzy,
    'extime_shandong_dongying_gcjs':extime_shandong_dongying_gcjs,
    'extime_sichuan_suining_ggzy':extime_sichuan_suining_ggzy,
    'extime_xizang_xizangsheng_ggzy':extime_xizang_xizangsheng_ggzy,
    'extime_qycg_b2b_10086_cn':extime_qycg_b2b_10086_cn,
    'extime_beijing_beijingshi_gcjs':extime_beijing_beijingshi_gcjs,
    'extime_gansu_wuwei_ggzy':extime_gansu_wuwei_ggzy,
    'extime_guangxi_qinzhou_zfcg':extime_guangxi_qinzhou_zfcg,
    'extime_heilongjiang_daqing_ggzy':extime_heilongjiang_daqing_ggzy,
    'extime_henan_henansheng_gcjs':extime_henan_henansheng_gcjs,
    'extime_hubei_macheng_ggzy':extime_hubei_macheng_ggzy,
    'extime_jiangsu_jiangsusheng_gcjs':extime_jiangsu_jiangsusheng_gcjs,
    'extime_liaoning_haicheng_ggzy':extime_liaoning_haicheng_ggzy,
    'extime_liaoning_liaoningsheng_ggzy':extime_liaoning_liaoningsheng_ggzy,
    'extime_qycg_fwgs_sinograin_com_cn':extime_qycg_fwgs_sinograin_com_cn,
    'extime_guangxi_guangxisheng_gcjs':extime_guangxi_guangxisheng_gcjs,
    'extime_liaoning_tieling_ggzy':extime_liaoning_tieling_ggzy,
    'extime_liaoning_liaoningsheng_zfcg':extime_liaoning_liaoningsheng_zfcg,
    'extime_sichuan_sichuansheng_daili':extime_sichuan_sichuansheng_daili,
    'extime_sichuan_mianzhu_zfcg':extime_sichuan_mianzhu_zfcg,
    'extime_sichuan_huaying_ggzy':extime_sichuan_huaying_ggzy,
    'extime_sichuan_chengdu_edu':extime_sichuan_chengdu_edu,
    'extime_jilin_changchun_edu':extime_jilin_changchun_edu,
    'extime_jiangsu_changzhou_edu':extime_jiangsu_changzhou_edu,
    'extime_hubei_shennongjia_ggzy':extime_hubei_shennongjia_ggzy,
    'extime_heilongjiang_heihe_wudalianchi_ggzy':extime_heilongjiang_heihe_wudalianchi_ggzy,
    'extime_daili_www_cobo91_com':extime_daili_www_cobo91_com,
    'extime_chongqing_shapingba_zfcg':extime_chongqing_shapingba_zfcg,
    'extime_daili_www_baili21_com':extime_daili_www_baili21_com,
    'extime_yunnan_yunnansheng_8_daili':extime_yunnan_yunnansheng_8_daili,
    'extime_hebei_hebeisheng_daili':extime_hebei_hebeisheng_daili,
    'extime_guangdong_shenzhen_6_daili':extime_guangdong_shenzhen_6_daili,
    'extime_guangdong_guangdongsheng_19_daili':extime_guangdong_guangdongsheng_19_daili,
    'extime_guangdong_guangdongsheng_21_daili':extime_guangdong_guangdongsheng_21_daili,
    'extime_guangdong_guangdongsheng_22_daili':extime_guangdong_guangdongsheng_22_daili,
    'extime_guangdong_guangdongsheng_24_daili':extime_guangdong_guangdongsheng_24_daili,
    'extime_jiangxi_jiangxisheng_2_daili':extime_jiangxi_jiangxisheng_2_daili,
    'extime_shandong_shandongsheng_4_daili':extime_shandong_shandongsheng_4_daili,
    'extime_tail1':extime_tail1,
    'extime_daili_www_zhengdapengan_com':extime_daili_www_zhengdapengan_com,
    'extime_daili_www_zjtaiyu_cn':extime_daili_www_zjtaiyu_cn,
    'extime_yunnan_yunnansheng_24_daili':extime_yunnan_yunnansheng_24_daili,
    'extime_tianjin_tianjinshi_1_edu':extime_tianjin_tianjinshi_1_edu,
    'extime_sichuan_sichuansheng_7_daili':extime_sichuan_sichuansheng_7_daili,
    'extime_sichuan_chengdu_3_edu':extime_sichuan_chengdu_3_edu,
    'extime_heilongjiang_heilongjiangsheng_3_daili':extime_heilongjiang_heilongjiangsheng_3_daili,
    'extime_hebei_zhangjiakou_zfcg':extime_hebei_zhangjiakou_zfcg,
    'extime_hebei_hebeisheng_2_daili':extime_hebei_hebeisheng_2_daili,
    'extime_guangdong_shenzhen_20_daili':extime_guangdong_shenzhen_20_daili,
    'extime_guangdong_huizhou_daili':extime_guangdong_huizhou_daili,
    'extime_gansu_lanzhou_edu':extime_gansu_lanzhou_edu,
    'extime_chongqing_chongqingshi_2_edu':extime_chongqing_chongqingshi_2_edu,
    'extime_beijing_beijingshi_5_edu':extime_beijing_beijingshi_5_edu,
    'extime_anhui_anhuisheng_3_daili':extime_anhui_anhuisheng_3_daili,
    'extime_qycg_zbpt_zjzttx_com_cn':extime_qycg_zbpt_zjzttx_com_cn,
    'extime_qycg_bid_sichuanair_com':extime_qycg_bid_sichuanair_com,
    ##func_name##:##func_name##
}
