
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-27T09:12:17-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a27060795a1535c71c8d8e2b510a173a7f04c40c",
 "version": "v0.6a10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
