
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-27T16:37:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f66f6392a1de87d3a7d018a1cf8cdab0185a503d",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
