[tool.poetry]
name = "swashbookler"
version = "1.0.2"
description = "Allows downloading books from Google Books and converting them to PDFs."
authors = ["Coriander Pines <incoming+cvpines-swashbookler-5856924-issue-@incoming.gitlab.com>"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/cvpines/swashbookler"
homepage = "https://gitlab.com/cvpines/swashbookler"

[tool.poetry.dependencies]
python = "^3.7"
beautifulsoup4 = "^4.8.0"
requests = "^2.22"
pillow = "^6.1"
img2pdf = "^0.3.3"
PyYAML = "^5.1"
click = "^7.0"

[tool.poetry.dev-dependencies]
mypy = "^0.720.0"
pytest = "^5.1"
tox = "^3.14"

[tool.poetry.scripts]
swashbookler = 'swashbookler.cli:cli'

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py37

[testenv]
whitelist_externals = poetry
commands =
    poetry install -vvv
    poetry run pytest tests/
"""

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
