# Generated by Django 2.1.4 on 2018-12-17 22:50

from django.db import migrations, models
import foreignform.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0002_auto_20181028_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchieDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='A title for this doc', max_length=250, verbose_name='Project title')),
                ('doc_id', models.SlugField(help_text='Doc ID from URL', verbose_name='Google Doc ID')),
                ('validation_schema', foreignform.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
