# Generated by Django 2.1.4 on 2018-12-18 03:19

from django.db import migrations
import foreignform.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0003_archiedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiedoc',
            name='validation_schema',
            field=foreignform.fields.JSONField(blank=True, help_text='JSON Schema', null=True),
        ),
    ]
