# Generated by Django 2.2.4 on 2019-08-25 21:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0004_auto_20181218_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='A title for this project', max_length=250, unique=True, verbose_name='Project title')),
            ],
        ),
        migrations.AddField(
            model_name='archiedoc',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archie_docs', to='kitchensink.Project'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sheets', to='kitchensink.Project'),
        ),
    ]
