# Generated by Django 2.2.6 on 2019-10-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0005_auto_20190825_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='sheet_id',
            new_name='google_id',
        ),
    ]
