# Generated by Django 2.2.6 on 2019-10-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0006_auto_20191002_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archiedoc',
            old_name='doc_id',
            new_name='google_id',
        ),
    ]
