# Generated by Django 2.2.6 on 2019-10-02 19:46

from django.db import migrations, models
import foreignform.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0007_auto_20191002_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiedoc',
            name='version',
            field=models.CharField(choices=[('v1', 'v1'), ('v2', 'v2')], default='v1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheet',
            name='validation_schema',
            field=foreignform.fields.JSONField(blank=True, help_text='JSON Schema', null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='version',
            field=models.CharField(choices=[('v1', 'v1'), ('v2', 'v2')], default='v1', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sheet',
            name='google_id',
            field=models.SlugField(help_text='Doc ID from URL', verbose_name='Google Doc ID'),
        ),
    ]
