# Generated by Django 2.2.6 on 2019-10-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchensink', '0009_auto_20191002_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiedoc',
            name='title',
            field=models.CharField(help_text='A title for this doc', max_length=250, verbose_name='Document title'),
        ),
    ]
