# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopstarter_data', '0003_auto_20191003_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneurs', to='coopstarter_data.Organisation'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='coopstarter_data.Country'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='coopstarter_data.Organisation'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
