[tool.poetry]
name = "djangorestcli"
version = "0.1.7"
description = ""
authors = ["Ronnasayd <Ronnasayd@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
