
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-11T10:01:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa47289f0de282ee384d675aa765cea528b13d0c",
 "version": "0.5.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
