- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - cyborg-tempest
        - cyborg-tempest-ipv6-only
    gate:
      queue: cyborg

- job:
    name: cyborg-tempest
    voting: false
    parent: devstack-tempest
    timeout: 7800
    required-projects: &base_required_projects
      - openstack/cyborg
      - openstack/python-cyborgclient
      - openstack/tempest
      - openstack/cyborg-tempest-plugin
    vars: &base_vars
      devstack_plugins:
        cyborg: https://opendev.org/openstack/cyborg
      devstack_services:
        tempest: true
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        tls-proxy: false
      devstack_localrc:
        TEMPEST_PLUGINS: "/opt/stack/cyborg-tempest-plugin"
      tempest_test_regex: cyborg_tempest_plugin
      tox_envlist: all
    irrelevant-files: &base_irrelevant_files
      - ^.*\.rst$
      - ^doc/.*$
      - ^setup.cfg$
      - ^releasenotes/.*$
      - ^(test-|)requirements.txt$
      - ^.git.*$
      - ^tox.ini$

- job:
    name: cyborg-tempest-ipv6-only
    parent: devstack-tempest-ipv6
    description: |
      Cyborg devstack tempest tests job for IPv6-only deployment
    voting: false
    timeout: 7800
    required-projects: *base_required_projects
    vars: *base_vars
    irrelevant-files: *base_irrelevant_files
