[tool.poetry]
name = "quotes-api"
version = "0.1.1"
description = ""
authors = ["guilhermevbeira <guilherme.vieira.beira@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"

[tool.poetry.dev-dependencies]
pre-commit = "^1.18"
vcrpy = "^2.1"
coverage = "^4.5"
pytest-cov = "^2.8"
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
