[tool.poetry]
name = "mecab2pandas"
version = "0.2.1"
description = "MeCab to pandas"
authors = ["Lucky <phatbowie@gmail.com>"]
homepage = "https://github.com/Lucky-Mano/mecab2pandas"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
mecab-python3 = "^0"
pandas = "^0"

[tool.poetry.dev-dependencies]
flake8 = "^3"
pydocstyle = "^3"
nose = "^1"
isort = "^4"
pre-commit = "^1"
mypy = "^0"
black = { version="^19", allows-prereleases = true }

[tool.black]
line-length = 100
target-version = ["py37"]
exclude = '''
(
  \.eggs
  | \.git
  | \.mypy_cache
  | \.pytest_cache
  | dist
)
'''

[tool.isort]
include_trailing_comma = true
line_length = 100
multi_line_output = 3

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
