
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-09-25T14:43:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "affb1d83af403a2fc306bfd188fce02e75fc5f2b",
 "version": "0.9.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
