dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: NK7VrXcgTamr1bUE34uJcmiy9x0fJtER28JvYqKaDkv3OXsf0uwWbwdQW2w8eemJIk96157DcsVXgaohqRv1MweltA3/fVtPr8jlqXWqaPPRohPbe5ove3mAIyYbXfa29du6y65sFQoebhbU3wW2LMqujnmU77Tl9+mR5n1zOuczVTHSx7/3mxUXSAYOpCJoHPazKJFbqwlF6qAGlPTorqBSFfpNK5Kt7hGBBe1cgWh4UKNrSDv6dCalGHdQPRI7xr4pjTxrOMaINt9d261gYk1rxC8S3RqSOtF/SF1kh1/IDEd0T+ZiRpXP8ynfw65XFh+McbczY+o0JpM8uQj58dKvKCEcNgD9u+z6bO4CPh3+YrPthNewzI0h3PW3ECgXKLqnVr1/WCyWncDz8NAk1QjLs97h1PTlHy9KodXQk4W5qb93agpCZrPbsGrbMTkJd3ElazQU0Yh0n1BntZNndnMeg5RPfWl5r0niRGS3JWEMGxPM9Wgutf/5hT9bpjzuQWovMRibc7zvPJQ9zUNzyZNstUM9FZFVrVBcX+v+Cph4FW1JESghv0vhhgapilhUSMIgUorarhQKv/B8iqRqpRF6nXbjMKBGb6DE+i68lzA/k4+Iz9QtUa4MOgR0qPR0BbPiI85vEM+LL7/cNBp+3xZ8CWWUAyQovzGb7NuPJ20=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_fancyled/*.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-fancyled --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
