- project:
    templates:
      - tempest-plugin-jobs
      - check-requirements
    check:
      jobs:
        - cloudkitty-tempest-full:
            voting: true
        - cloudkitty-tempest-full-python3:
            voting: true
    gate:
      queue: cloudkitty
      jobs:
        - cloudkitty-tempest-full:
            voting: true
        - cloudkitty-tempest-full-python3:
            voting: true
