#name: pythonExperiment
#channels:
#  - javascript
dependencies:
  - python=3.7   # or 2.7 or 3.5 or 3.6
  - pip
  - numpy
  - matplotlib
  - requests[socks]

#  - pip:
#     - xanity
#  - bokeh=0.9.2
#  - scipy
#  - scikit-learn
#  - nodejs=0.10.*
#  - flask
#  - pip:
#     - dill
#     - "--editable=git+ssh://git@github.gatech.edu/LARS/d3cida.git#egg=decida"
#     - "git+ssh://git@github.gatech.edu/LARS/libpsf.git#egg=libpsf"

#  if using the above for fetching from github, BE SURE TO REPLACE the colon (:) in the url with a slash (/) !!!!!!!!!!!!!
