
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-09T20:18:14+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfb905ffc65a6005ca700d9accc19e5759f18f43",
 "version": "0.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
