
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-01T15:50:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9090833cfbac2bf7b4fb4944185a8d69d09f88aa",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
