
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-03T08:43:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d94ecf9f33b0e76fddc17951c93a1a157fe52c86",
 "version": "v0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
