
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-07T03:15:06-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "46f2ee648ace0b404c3d62b18fe4e2278c211424",
 "version": "0+untagged.571.g46f2ee6.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
