[tool.poetry]
name = "testpoetrypypi"
version = "0.1.0"
description = ""
authors = ["Jeff"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.scripts]
runtest = "runtest:main"
testpoetrypypi = "testpoetrypypi:main"


[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
